export interface Validator {
  pubKey: string;
  name: string;
  iconUrl: string;
  brandColor: string;
}

export const TOP_VALIDATORS: Validator[] = [
  { pubKey: "he1iusunGwqrNtafDtLdhsUQDFvo13z9sUa36PauBtk", name: "Helius", iconUrl: "helius.svg", brandColor: "rgb(232,67,38)" },
  { pubKey: "CatzoSMUkTRidT5DwBxAC2pEtnwMBTpkCepHkFgZDiqb", name: "Jupiter", iconUrl: "jupiter.svg", brandColor: "rgb(199,242,132)" },
  { pubKey: "CcaHc2L43ZWjwCHART3oZoJvHLAe9hzT2DJNUpBzoTN1", name: "Figment", iconUrl: "", brandColor: "rgb(255,248,80)" },
  { pubKey: "3N7s9zXMZ4QqvHQR15t5GNHyqc89KduzMP7423eWiD5g", name: "Binance Staking", iconUrl: "binance-staking.svg", brandColor: "rgb(240,185,11)" },
  { pubKey: "26pV97Ce83ZQ6Kz9XT4td8tdoUFPTng8Fb8gPyc53dJx", name: "Ledger by Figment", iconUrl: "ledger.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "DdCNGDpP7qMgoAy6paFzhhak2EeyCZcgjH7ak5u5v28m", name: "Kiln1", iconUrl: "kiln.svg", brandColor: "rgb(255,101,33)" },
  { pubKey: "3JD3jMmnR6g88qff2WZ3cMHJRjJMUk9yVZtmYTYeFrXf", name: "Forward Industries", iconUrl: "forward-industries.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "CvSb7wdQAFpHuSpTYTJnX5SYH4hCfQ9VuGnqrKaKwycB", name: "Galaxy", iconUrl: "galaxy.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF", name: "Everstake", iconUrl: "everstake.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "DumiCKHVqoCQKD8roLApzR5Fit8qGV5fVQsJV9sTZk4a", name: "Staking Facilities", iconUrl: "staking-facilities.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "51JBzSTU5rAM8gLAVQKgp4WoZerQcSqWC7BitBzgUNAm", name: "Kraken 2", iconUrl: "kraken.svg", brandColor: "rgb(113,50,245)" },
  { pubKey: "8GbwASqdpw4dVcwbWUxbHXMrjyQx2aKkoBR5H1GJF8iD", name: "Bitwise Onchain Solutions", iconUrl: "bitwise.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "GHViLgbrJdZDPb6sphRbeuPNM9cmjsFuGWzrTF1sKF5n", name: "Upbit Staking", iconUrl: "upbit.svg", brandColor: "rgb(0,98,223)" },
  { pubKey: "Chorus6Kis8tFHA7AowrPMcRJk3LbApHTYpgSNXzY5KE", name: "Chorus One", iconUrl: "chorus-one.svg", brandColor: "rgb(22,143,156)" },
  { pubKey: "shft7Fry1js37Hm9wq4dfwcZSp2DyKszeWMvEpjYCQ1", name: "Blueshift", iconUrl: "blueshift.svg", brandColor: "rgb(0,255,255)" },
  { pubKey: "FKsC411dik9ktS6xPADxs4Fk2SCENvAiuccQHLAPndvk", name: "P2P.org", iconUrl: "p2p-org.svg", brandColor: "rgb(43,89,255)" },
  { pubKey: "Ak5BJzQe2R8qFuyYmaAFPjXuD7XPux3ZNTv52D7rfiqR", name: "Twinstake", iconUrl: "twinstake.svg", brandColor: "rgb(255,120,66)" },
  { pubKey: "GqcuMuWq4gKeCuCrD8iAjXTozCET2EP6qJXmZDFsSTWK", name: "Coinbase 03", iconUrl: "coinbase.svg", brandColor: "rgb(0,82,255)" },
  { pubKey: "AaVsZUEnrHUZoXC2oVgTY3GF5GGhzCTBGrjpBtuUWy1H", name: "Coinbase 04", iconUrl: "coinbase.svg", brandColor: "rgb(0,82,255)" },
  { pubKey: "KRAKEnMdmT4EfM8ykTFH6yLoCd5vNLcQvJwF66Y2dag", name: "Kraken", iconUrl: "kraken.svg", brandColor: "rgb(113,50,245)" },
  { pubKey: "6D2jqw9hyVCpppZexquxa74Fn33rJzzBx38T58VucHx9", name: "Coinbase 02", iconUrl: "coinbase.svg", brandColor: "rgb(0,82,255)" },
  { pubKey: "6aow5rTURdbhbeMDrFrbP2GR5vZjMEhktEy87iH1VGPs", name: "Luganodes", iconUrl: "luganodes.svg", brandColor: "rgb(190,30,46)" },
  { pubKey: "2NxEEbhqqj1Qptq5LXLbDTP5tLa9f7PqkU8zNgxbGU9P", name: "Nansen", iconUrl: "nansen.svg", brandColor: "rgb(0,255,167)" },
  { pubKey: "9Diao4uo6NpeMud7t5wvGnJ3WxDM7iaYxkGtJM36T4dy", name: "Firedancer Development", iconUrl: "firedancer.svg", brandColor: "rgb(28,231,194)" },
  { pubKey: "FQwewNXahV7MiZcLpY6p1xhUs2acVGQ3U5Xxc7FzV571", name: "Blockdaemon Validator", iconUrl: "blockdaemon.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "DriFTm3wM9ugxhCA1K3wVQMSdC4Dv4LNmyZMmZiuHRpp", name: "Drift", iconUrl: "drift.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "2tucttroqFNXsrYeMBQ8LfzKNfgwT2rHBzAF6RzbbHEp", name: "OKX Earn", iconUrl: "okx-earn.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "JEJzKYzyYJJjtn6Yb1P7r6YV75TdSNmmJT49sgDoHvmk", name: "Alchemy", iconUrl: "alchemy.svg", brandColor: "rgb(54,63,249)" },
  { pubKey: "4AUED4uj6nSTuANzaAUnGBPJQRmhpDYDwoWJNkoUUBBW", name: "Anagram Staking", iconUrl: "anagram.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "AS3nKBQfKs8fJ8ncyHrdvo4FDT6S8HMRhD75JjCcyr1t", name: "Overclock", iconUrl: "overclock.svg", brandColor: "rgb(3,193,135)" },
  { pubKey: "HxRrsnbc6K8CdEo3LCTrSUkFaDDxv9BdJsTDzBKnUVWH", name: "Haus", iconUrl: "haus.svg", brandColor: "rgb(205,248,0)" },
  { pubKey: "8hPk5CbKDoM7dN9LssTdVkFhDykeq7A8CZurA5AQSFJH", name: "Bybit Staking", iconUrl: "bybit.svg", brandColor: "rgb(246,165,0)" },
  { pubKey: "ERut3CwqVeoa616QBaoHc5jL52RpkXjZZZ7MeaMaCtLi", name: "Coinbase 05", iconUrl: "coinbase.svg", brandColor: "rgb(0,82,255)" },
  { pubKey: "beefKGBWeSpHzYBHZXwp5So7wdQGX6mu4ZHCsH3uTar", name: "Coinbase", iconUrl: "coinbase.svg", brandColor: "rgb(0,82,255)" },
  { pubKey: "GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e", name: "Melea", iconUrl: "melea.webp", brandColor: "rgb(0,255,255)" },
  { pubKey: "Haz7b47sZBpxh9SwggGndN3fAyNQ1S949BPdxWXS3ab6", name: "Temporal Emerald", iconUrl: "temporal.svg", brandColor: "rgb(11,241,155)" },
  { pubKey: "BLADE1qNA1uNjRgER6DtUFf7FU3c1TWLLdpPeEcKatZ2", name: "Shinobi Systems", iconUrl: "shinobi-systems.svg", brandColor: "rgb(207,136,1)" },
  { pubKey: "EXhYxF25PJEHb3v5G1HY8Jn8Jm7bRjJtaxEghGrUuhQw", name: "Solflare", iconUrl: "solflare.svg", brandColor: "rgb(255,239,70)" },
  { pubKey: "EARNynHRWg6GfyJCmrrizcZxARB3HVzcaasvNa8kBS72", name: "Solana Compass", iconUrl: "solana-compass.wepb", brandColor: "rgb(255,255,255)" },
  { pubKey: "Bwkz1ddKoGE8hgiSV6HZLXi9RBLqfBi3HZb2QujzVGgz", name: "StakeBowl", iconUrl: "stakebowl.webp", brandColor: "rgb(60,219,192)" },
  { pubKey: "23XqhxnRHt5gQWHowvyRHDX4Ky6BZyFdYxjTzxx2QEFr", name: "OtterSec", iconUrl: "ottersec.svg", brandColor: "rgb(255,255,255)" },
  { pubKey: "xBLpiTwufjcuFCjbk4aCmFy7HUY5D9xy8L1EX2rBwmC", name: "P2P.org Turbo", iconUrl: "p2p-org.svg", brandColor: "rgb(43,89,255)" },
  { pubKey: "VotESBSkLKU8vebS6wTR2rzWWJsLc6YThYS6tebPxXq", name: "Paragon", iconUrl: "paragon.svg", brandColor: "rgb(238,241,238)" },

  { pubKey: "g5kwi5sFXQTx26jwetYK97ytvx1WpA1RWuQ82Afdzyn", name: "Blockman", iconUrl: "", brandColor: "" },
  { pubKey: "7S9dHgoeMYvtShTjEC3x5D3THRDQz123WVGPseZsm3hm", name: "Rocket", iconUrl: "", brandColor: "" },
  { pubKey: "5sMmkL4BXjU6vZXQxE3RquH2CR8v8Zbfi1EAAFxLfxMx", name: "Alpha", iconUrl: "", brandColor: "" },
  { pubKey: "8UHnwrLihP4q1fZjAYGCZdGgtAkCaFiDLXa33r7niRjD", name: "AP Node", iconUrl: "", brandColor: "" },
  { pubKey: "8uEgdseqbUrDLfmHbUpTHoH1LLRxeViYDk7K6NdXKRYM", name: "Hamsa", iconUrl: "", brandColor: "" },
  { pubKey: "3tUZu4CkwMLwYdosoGc85n48VgDMyxZVkL1VUJc7DrxW", name: "Flash", iconUrl: "", brandColor: "" },
  { pubKey: "5s3vajJvaAbabQvxFdiMfg14y23b2jvK6K2Mw4PYcYK", name: "Quicknode", iconUrl: "", brandColor: "" },
  { pubKey: "5orRi4tMEGneZ9U2y381JnBEnsqFJDBSNQLhBn98Bkcv", name: "Quatro", iconUrl: "", brandColor: "" },
  { pubKey: "AiDoLYTz5CVN3ZLzqDWRtaGUaHGzDnWMeC6KCNYJPqFX", name: "AiDoL", iconUrl: "", brandColor: "" },
  { pubKey: "CooLbbZy5Xmdt7DiHPQ3ss2uRXawnTXXVgpMS8E8jDzr", name: "Cavey Cool", iconUrl: "", brandColor: "" },
  { pubKey: "Ha1VoTEPWFQp1wZjbQhBNXJftuHvimu1ruzF3xKYRPDQ", name: "Ha1iad3", iconUrl: "", brandColor: "" },
  { pubKey: "oRAnGeU5h8h2UkvbfnE5cjXnnAa4rBoaxmS4kbFymSe", name: "Orangefin", iconUrl: "", brandColor: "" },
  { pubKey: "LSTmLs1DENX82ihc7jU134mydiV3NDEPXsRrekAY6Ys", name: "Sanctum", iconUrl: "", brandColor: "" },
  { pubKey: "6XiVWAyRpG7wGUQPVRd2XrYdgQVQyoQamd2J8XAmate", name: "Solmate", iconUrl: "", brandColor: "" },
  { pubKey: "7opSZGmevWhRDyLt5Wu38FZFjUyredGmMki4DNmxDnjd", name: "Alpha Pro", iconUrl: "", brandColor: "" },
  { pubKey: "6F5xdRXh2W3B2vhte12VG79JVUkUSLYrHydGX1SAadfZ", name: "Allnodes", iconUrl: "", brandColor: "" },
  { pubKey: "DQ7D6ZRtKbBSxCcAunEkoTzQhCBKLPdzTjPRRnM6wo1f", name: "StakeWolf", iconUrl: "", brandColor: "" },
  { pubKey: "HMV14UAuULSwqmZhsKHzaVkYAd94iWpEeURgbUegfQLc", name: "Hello Moon", iconUrl: "", brandColor: "" },
  { pubKey: "juicQdAnksqZ5Yb8NQwCLjLWhykvXGktxnQCDvMe6Nx", name: "ProStaking", iconUrl: "", brandColor: "" },
  { pubKey: "9jYFwBfbjYmvasFbJyES9apLJDTkwtbgSDRWanHEvcRw", name: "Watchtower", iconUrl: "", brandColor: "" },
  { pubKey: "8zHJtME22tiY3UsSHtDJXo2J8hUfwikBxXNbVqQzA92r", name: "Bella2.0", iconUrl: "", brandColor: "" },
  { pubKey: "CogentC52e7kktFfWHwsqSmr8LiS1yAtfqhHcftCPcBJ", name: "Cogent", iconUrl: "", brandColor: "" },
  { pubKey: "BbM5kJgrwEj3tYFfBPnjcARB54wDUHkXmLUTkazUmt2x", name: "Solana Validator", iconUrl: "", brandColor: "" },
  { pubKey: "RBFvvcGPBpgkBYmJGsphoDQJD8sszSuorM7TorWm12Y", name: "RockawayX Infra", iconUrl: "", brandColor: "" },
  { pubKey: "SKRuTecmFDZHjs2DxRTJNEK7m7hunKGTWJiaZ3tMVVA", name: "Solana Mobile Validator", iconUrl: "", brandColor: "" },
  { pubKey: "Va1idkzkB6LEmVFmxWbWU8Ao9qehC62Tjmf68L3uYKj", name: "validator.com", iconUrl: "", brandColor: "" },
  { pubKey: "FiijvR2ibXEHaFqB127CxrL3vSj19K2Kx1jf2RbK4BWS", name: "Trust Nodes", iconUrl: "", brandColor: "" },
  { pubKey: "Pond1QyT1sQtiru3fi9G5LGaLRGeUpJKR1a2gdbq2u4", name: "Leapfrog Systems", iconUrl: "", brandColor: "" },
  { pubKey: "HCvnhbT3Sn5RsueDisWzzn5FkW8tAqoQK1dr7cvAVzin", name: "Kiln2", iconUrl: "", brandColor: "" },
  { pubKey: "7VGU4ZwR1e1AFekqbqv2gvjeg47e1PwMPm4BfLt6rxNk", name: "Stakefish", iconUrl: "", brandColor: "" },
  { pubKey: "RNXpSdqrJL6eoLrbW69Q9qsFviEwRpfFfk3HiRRRohq", name: "RockawayX Firedancer", iconUrl: "", brandColor: "" },
  { pubKey: "BeachiopjxQxL7CaHNSZsynApiZCKx9QFVtcWNz3jDBo", name: "Solana Beach Validator", iconUrl: "", brandColor: "" },
  { pubKey: "5iJDEVRi1nMLwKAWhYbEokZnvBAe15rgFaHGkggVEP9z", name: "Stardust Staking", iconUrl: "", brandColor: "" },
  { pubKey: "DqbRPQXbN8GDKWZkKiHnRjiSKPqE3rQaNgTPxdLGPDMK", name: "Axiom", iconUrl: "", brandColor: "" },
  { pubKey: "oPaLTmyvoUhW26QCMwLA5JNUeBYy72PDpFoXQF8SeX4", name: "Temporal Opal", iconUrl: "", brandColor: "" },
  { pubKey: "GREEDkpTvpKzcGvBu9qd36yk6BfjTWPShB67gLWuixMv", name: "GREED Academy", iconUrl: "", brandColor: "" },
  { pubKey: "GE6atKoWiQ2pt3zL7N13pjNHjdLVys8LinG8qeJLcAiL", name: "Laine", iconUrl: "", brandColor: "" },
  { pubKey: "2HQ5YHuw8cR1erRYZmemDmQVpfEMCjAvwU7V4fgdemJB", name: "Gate Earn", iconUrl: "", brandColor: "" },
  { pubKey: "CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu", name: "Asymmetric Research", iconUrl: "", brandColor: "" },
  { pubKey: "mnvkHm47ZmRKoSWuQZAfXLRiDPiKCq8PWkMWrp1Wwqe", name: "gripto", iconUrl: "", brandColor: "" },
  { pubKey: "9GJmEHGom9eWo4np4L5vC6b6ri1Df2xN8KFoWixvD1Bs", name: "Block Logic", iconUrl: "", brandColor: "" },
  { pubKey: "EcLPNfLFgCkbcTuvdeQ85pnQMgAfBDqi2dkoNVPrSyr5", name: "Bitcoin Suisse", iconUrl: "", brandColor: "" },
  { pubKey: "CAf8jfgqhia5VNrEF4A7Y9VLD3numMq9DVSceq7cPhNY", name: "Chainflow", iconUrl: "", brandColor: "" },
  { pubKey: "gaToR246dheK1DGAMEqxMdBJZwU4qFyt7DzhSwAHFWF", name: "Valigator Open", iconUrl: "", brandColor: "" },
  { pubKey: "EeitHdhXPu3pYMb5oPHvLjkaKQMUPzdNnxvrXc3EEHxj", name: "STSS Validator", iconUrl: "", brandColor: "" },
  { pubKey: "ANCVpxEySGWWLqqkVKw2xWYDE9UP4fmZWMCBr5t96jch", name: "Anchorage Digital", iconUrl: "", brandColor: "" },
  { pubKey: "TXTXAmsarrYrTobiCzq2r9NBqfChqRE8wEfJNsYZZ6F", name: "txtx", iconUrl: "", brandColor: "" },
  { pubKey: "mrgn4t2JabSgvGnrCaHXMvz8ocr4F52scsxJnkQMQsQ", name: "Project 0 Meridian", iconUrl: "", brandColor: "" },
  { pubKey: "DierScgiTrz5AM7mddeJLHYNvafym3XhjjdM51AnKevU", name: "Pier Two", iconUrl: "", brandColor: "" },
  { pubKey: "bkpkQKgJMQXqwZL5dRX9LMwnsz9zkZZqCtqWfnBcwDx", name: "Backpack", iconUrl: "", brandColor: "" },
  { pubKey: "6q1VNp8Vy2Go12vb8CwbjUqqj2SXr2JYftJRWs71sW23", name: "Exo Tech", iconUrl: "", brandColor: "" },
  { pubKey: "BxFf75Vtzro2Hy3coFHKxFMZo5au8W7J8BmLC3gCMotU", name: "Chainode Tech", iconUrl: "", brandColor: "" },
  { pubKey: "DMSuZcavta8L1w1tSiH8bALWjz6Q6KSryGG6m6Az4Qt5", name: "Lion3d", iconUrl: "", brandColor: "" },
  { pubKey: "voteRnv6PBzmiGP8NicWtQiqEJTwKKq2SxtqtdLUJjd", name: "diman", iconUrl: "", brandColor: "" },
  { pubKey: "anza1Vgz2kcN9Qo6ECvf43v8RxBzQ7UpvxFoxJtLmGz", name: "Anza", iconUrl: "", brandColor: "" },
  { pubKey: "SLaYv7tCwetrFGbPCRnqpHswG5qqKino78EYpbGF7xY", name: "Solayer Validator", iconUrl: "", brandColor: "" },
  { pubKey: "mintrNtxN3PhAB45Pt41XqyKghTTpqcoBkQTZqh96iR", name: "Hanabi Staking", iconUrl: "", brandColor: "" },
  { pubKey: "528hi3StRe7uGjt99d35myh95JPc2MqBEHTPYcEhqMg5", name: "Blueprint", iconUrl: "", brandColor: "" },
  { pubKey: "2ZP7DPXW6gwMRSY9PSXQ75fZLrk4gKWKnT85pK5sVPa5", name: "Tinydancer", iconUrl: "", brandColor: "" },
  { pubKey: "HLXktVmNFeELB5uL5nrpP4WL7jyi3TMyekxASVjDhZ1t", name: "HelixNode", iconUrl: "", brandColor: "" },
  { pubKey: "hy1oJTV2kX9acsqpwk7hbteqXFw9VDbWvbxoamFEufW", name: "Hylo", iconUrl: "", brandColor: "" },
  { pubKey: "J1to2NAwajc8hD6E6kujdQiPn1Bbt2mGKKZLY9kSQKdB", name: "Jito2", iconUrl: "", brandColor: "" },
  { pubKey: "BULKEEKf9Hjy4nwCthjzheEk4joH23LLXttAHjqEZmB2", name: "BULK", iconUrl: "", brandColor: "" },
  { pubKey: "7emL18Bnve7wbYE9Az7vYJjikxN6YPU81igf6rVU5FN8", name: "Temporal Topaz", iconUrl: "", brandColor: "" },
  { pubKey: "MARvNLH6rCLroQEGr8fWNxygJ7fHJRCfykRk9DqzwVn", name: "USDG", iconUrl: "", brandColor: "" },
  { pubKey: "J1to1yufRnoWn81KYg1XkTWzmKjnYSnmE2VY8DGUJ9Qv", name: "Jito 1", iconUrl: "", brandColor: "" },
  { pubKey: "HJmfKJjKiyuuxFUuXgecgD5gdD312apCpHwZt6ETuRMU", name: "Ghost", iconUrl: "", brandColor: "" },
  { pubKey: "punK4RDD3pFbcum79ACHatYPLLE1hr5UNnQVUGNfeyP", name: "SOL Strategies", iconUrl: "", brandColor: "" },
  { pubKey: "NDf9Pv6TAxTDPR6ud3djsd2Ux1WS2m2YfTw4qEmSnQH", name: "Astraeus", iconUrl: "", brandColor: "" },
  { pubKey: "47hzyKgoz9Fu1HP4mR48tvAFj7akCFZKGzZqWo32sNqG", name: "Maera", iconUrl: "", brandColor: "" },
  { pubKey: "BH2PMb9vuHxkVFMMHbH8iudCoBfUoX5tVaHfnEkKJ2gQ", name: "Bubbles", iconUrl: "", brandColor: "" },
  { pubKey: "1Dadio3JRvpEjY6iSmXmhbGy9RiU8Nxh2GmoVbNusbE", name: "1dad", iconUrl: "", brandColor: "" },
  { pubKey: "ALPHAthakWdoUxXJP6z8cjCkwrufcARXqi34EjShtFVT", name: "Alphasearch", iconUrl: "", brandColor: "" },
  { pubKey: "soLStAckuvkHtNzHF1cwmeSRG1FzVxKxwsdWZ1yrHrz", name: "SolStack", iconUrl: "", brandColor: "" },
  { pubKey: "Ste11vRHQJyQjcTKrDbTWAYsTXkX6PCnoEw3mSH3u2k", name: "Stellium", iconUrl: "", brandColor: "" },
  { pubKey: "BoNKvwirX136zCjcnayEM4W82vn13RKkjm1Sy3UPBdim", name: "BONK", iconUrl: "", brandColor: "" },
  { pubKey: "nymsndUdAZyUPpWYz5VEg8Ghj9cFvwTRgciLogpmYaQ", name: "Hypo Nyms", iconUrl: "", brandColor: "" },
  { pubKey: "CCxSNvJogH6LWyoiEbG7JfcWybw2FqqCExs5GuemChGr", name: "KlaustinMB", iconUrl: "", brandColor: "" },
  { pubKey: "FRTcwF2LHHLV2VxKB9nzNpqyBXjpKvkEs5aRuMXrrk8X", name: "Calypso", iconUrl: "", brandColor: "" },
  { pubKey: "9sWYTuuR4s12Q4SuSfo5CfWaFggQwA6Z8pf8dWowN5rk", name: "Ubik Capital", iconUrl: "", brandColor: "" },
  { pubKey: "BN6EvLCeuYdrTjGaHCyugF7sSH5uckoVoy3Kg2TkyuDW", name: "Sygnum Validators", iconUrl: "", brandColor: "" },
  { pubKey: "78QvBqfkWbDbyo1DMb2ku42r1UfxecwptjbPWJqxkX6E", name: "Appleyello", iconUrl: "", brandColor: "" },
  { pubKey: "5iZ5PQPy5Z9XDnkfoWPi6nvUgtxWnRFwZ36WaftPuaVM", name: "Pigs in Blankets", iconUrl: "", brandColor: "" },
  { pubKey: "Ec55BotYhWgC3xRmZ2UpuJvyySwxZeUrvEDPrxxG7r9B", name: "QubitNexus", iconUrl: "", brandColor: "" },
  { pubKey: "D3wscqsBCJGFzzoB7dB7wQfJzSEFVzu8Rxugfnfk7rdm", name: "Orbyval", iconUrl: "", brandColor: "" },
  { pubKey: "2NXwP6K1ityVnvK575SY7KdoEkvPHrfcRLY7BJRBk4ht", name: "Aurora Staking", iconUrl: "", brandColor: "" },
  { pubKey: "FrtCZRajYfrdoZarPxCsUB6f66ga5DPSXGz4F7VKyfKP", name: "Neumann", iconUrl: "", brandColor: "" },
  { pubKey: "7sBYPueerpq3kKjmuimJkGr7jmiM8ZZ74pXPMEcBSxo5", name: "InfraMesh", iconUrl: "", brandColor: "" },
  { pubKey: "6SF5cmEXFFEmnFd5BwM4J6NkZhh3WfPkgmqdoAGjLLPX", name: "livechanger", iconUrl: "", brandColor: "" },
  { pubKey: "J2nUHEAgZFRyuJbFjdqPrAa9gyWDuc7hErtDQHPhsYRp", name: "Phantom Validator", iconUrl: "", brandColor: "" },
  { pubKey: "DTwEEF6VSrmTBYkDcj3BKAc52qhvP8CEQUEAMMT1cG3", name: "Capital Alliance", iconUrl: "", brandColor: "" },
  { pubKey: "Eajfs6oXGGkvjYsxkQZZJcDCLLkUajaHizfgg2xTsqyd", name: "JM", iconUrl: "", brandColor: "" },
  { pubKey: "FdGcvmbpebUwYA3vSywnagsaC3Tq3pAVmcR6VoxVcdV9", name: "GlobalStake [Bare Metal]", iconUrl: "", brandColor: "" },
  { pubKey: "A11pGbZDE8fPNZgiqDjoST6v3QMdhzZ3r8W5YahCKtS5", name: "Rain Works", iconUrl: "", brandColor: "" },
  { pubKey: "R4spmF6oFW6wMQHv9L3PCEKumkspN3nveQihWyDAdRy", name: "Albert is Great", iconUrl: "", brandColor: "" },
  { pubKey: "AX6v1G9GH7FNcoX6ogNyoD2fZiLaNps7heL9RrGUYGC8", name: "FalconX", iconUrl: "", brandColor: "" },
  { pubKey: "edu1fZt5i82cFm6ujUoyXLMdujWxZyWYC8fkydWHRNT", name: "Low Fee Validation", iconUrl: "", brandColor: "" },
  { pubKey: "LAKEuKJQYVFpf4vyjX7iuf9ajHo3k9FiyewYKf6VxPV", name: "LakeStake", iconUrl: "", brandColor: "" },
  { pubKey: "SyNdica7qx3njeVKNgXvV7KC1NjPYNS4fyb3NxgevLH", name: "Syndica", iconUrl: "", brandColor: "" },
  { pubKey: "D3QPJm7BDzzPeRG51YZSEz3LfV7GvFNu9NkcibzURxuj", name: "Starke Finance", iconUrl: "", brandColor: "" },
  { pubKey: "A5ed2x2wEuHW8KsuhbSaTFU4CYT3WgHfQcwyQXz5SdDw", name: "Certora Validator", iconUrl: "", brandColor: "" },
  { pubKey: "radYEig9KGrMTMWbWRFV7LStotQbnLgPaEFHVDsudQz", name: "Radiants", iconUrl: "", brandColor: "" },
  { pubKey: "538iREQi6JxNqDHsMJRAJJ1ZqDQ2tvYuS8tfhtb7BaGu", name: "Super Validator", iconUrl: "", brandColor: "" },
  { pubKey: "EdGevanAjM8a6Gg9KxBVrmVdZAUGAZ9xaVd7t9R4H2x", name: "Edgevana", iconUrl: "", brandColor: "" },
  { pubKey: "49DJjUX3cwFvaZD5rCAwubiz7qdRWDez9xmB381XdHru", name: "Staker Space", iconUrl: "", brandColor: "" },
  { pubKey: "2s2K5hcECd67832EzrVMCiCtbb54CHsqXtewuwwNVqtA", name: "Nemertes", iconUrl: "", brandColor: "" },
  { pubKey: "CTDGxxJBrZVqUUHdHopLn4k4gtc2PCpcM9TB7ZEC4Hu2", name: "Cointelegraph Decentralization Guardians", iconUrl: "", brandColor: "" },
  { pubKey: "7qTwituXJJ5dtUwBZXjMNgtAyXJbx3X8V4B9gXFRjK9d", name: "P2P.org Labs", iconUrl: "", brandColor: "" },
  { pubKey: "3ZUQekqiZoybB57y49eqtvSaoonqDwuNbeqEGwN88JkQ", name: "Paws", iconUrl: "", brandColor: "" },
  { pubKey: "ErvMUdtMC7AX55zKdYSyy4DnWNCrTsWn5GwprSG7ocnx", name: "CatalystX", iconUrl: "", brandColor: "" },
  { pubKey: "BeSov1og3sEYyH9JY3ap7QcQDvVX8f4sugfNPf9YLkcV", name: "Yonta Labs", iconUrl: "", brandColor: "" },
  { pubKey: "9G19HT8xqceG7mKQVSrTRS3DGnGqDHErPyQEaEfyWEuW", name: "Absolute Guard", iconUrl: "", brandColor: "" },
  { pubKey: "9RXDftY5xyhtYyzk4z7U9ddvBF2Z8DMfXmV6P6du9dxS", name: "KAST", iconUrl: "", brandColor: "" },
  { pubKey: "H2tJNyMHnRF6ahCQLQ1sSycM4FGchymuzyYzUqKEuydk", name: "Meria", iconUrl: "", brandColor: "" },
  { pubKey: "bXr9MyoUAaGusQZ4gaUPmSZByHAV7RRGr1FhCW5tFh8", name: "bloXroute EU", iconUrl: "", brandColor: "" },
  { pubKey: "THWfRpcJSC7oDrNMSCcixTZmCHVBTEVQL4qnd1UTD1x", name: "THW Validator", iconUrl: "", brandColor: "" },
  { pubKey: "phz34EcgWRCT9otPzRS2JtSzVHxQJk4SovqJvV1TQk8", name: "Netrunner", iconUrl: "", brandColor: "" },
  { pubKey: "HeTyhZdUKswQoonJJTXqAnDN48ceyVAeFaKfYKayGPNS", name: "Code-Breader", iconUrl: "", brandColor: "" },
  { pubKey: "4ibf8qJirtoBGg7gSD7V7CeCKoFB96PBYQ3J5QjSmAob", name: "Splash", iconUrl: "", brandColor: "" },
  { pubKey: "Ev3gPXRo6TJeQ2QhxfqWFoasdoGbmDytYvJbUabEHfLf", name: "Chive", iconUrl: "", brandColor: "" },
  { pubKey: "4PsiLMyoUQ7QRn1FFiFCvej4hsUTFzfvJnyN4bj1tmSN", name: "Stakin by The Tie", iconUrl: "", brandColor: "" },
  { pubKey: "3vwstewNgWAwN2uyuJduoZVVhmiwvAbwCxrjeJG6bASy", name: "JICO", iconUrl: "", brandColor: "" },
  { pubKey: "48oxpSHQkM4sdXUY9NQ8KnEtebzZbyk8uUT7JRdVQNuf", name: "lux8.net", iconUrl: "", brandColor: "" },
  { pubKey: "DPmsofVJ1UMRZADgwYAHotJnazMwohHzRHSoomL6Qcao", name: "JStaking", iconUrl: "", brandColor: "" },
  { pubKey: "3xjfK9C9YNcta8MvK1US4sQ3bc6DEjoJoR3qLExGf9xE", name: "pico.sol", iconUrl: "", brandColor: "" },
  { pubKey: "9wQQnnnkk5b5GkQWTW9L4kEA3CjFv6CqsQd5gt6tRsHK", name: "S4Mar", iconUrl: "", brandColor: "" },
  { pubKey: "CpfvLiiPALdzZTP3fUrALg2TXwEDSAknRh1sn5JCt9Sr", name: "Ledger by Chorus One", iconUrl: "", brandColor: "" },
  { pubKey: "6JfBwvcz5QUKQJ37BMKTLrf968DDJBtwoZLw19aHwFtQ", name: "Spectrum Staking", iconUrl: "", brandColor: "" },
  { pubKey: "EBVj3uwSKZpqEb1K267JaPxDQhULVqCy6hYeQqjsPh81", name: "Titan Analytics", iconUrl: "", brandColor: "" },
  { pubKey: "GA2t11gJcmuZ4y7pShTzgYDkxVaJaVQJqkVUqojhPPsT", name: "SolBrothers", iconUrl: "", brandColor: "" },
  { pubKey: "Simpj3KyRQmpRkXuBvCQFS7DBBG6vqw93SkZb9UD1hp", name: "Simpdigit", iconUrl: "", brandColor: "" },
  { pubKey: "gridZ5cMHjWGktAQt6o36NtF7XSv19nJBrW83zmo7BM", name: "Grid Systems", iconUrl: "", brandColor: "" },
  { pubKey: "6W8yrMwtDU5G6ErazhZHfLjqZV8cMvajpSRGYgrZ3d4v", name: "Legends", iconUrl: "", brandColor: "" },
  { pubKey: "1234LB7uvDC23rdCQoK8C3jNwnovUNyeKxz8wC3dghJ5", name: "BlueLotus", iconUrl: "", brandColor: "" },
  { pubKey: "3hhEWRNAVzqRjmF9hW5nYkrmDMxKKzGziE11Sg7yk3iX", name: "Glory to Ukraine", iconUrl: "", brandColor: "" },
  { pubKey: "tri1cHBy47fPyhCvrCf6FnR7Mz6XdSoSBah2FsZVQeT", name: "Trillium", iconUrl: "", brandColor: "" },
  { pubKey: "PUFFiNkUHF2DMfbKeUcYTSQckDDtkswfxZCDv5WQqwp", name: "Puffin", iconUrl: "", brandColor: "" },
  { pubKey: "J4pH3yiFrzFG1AQPRGBJXo3HP72MCZwsQamtp9ym4LwN", name: "Dosirak", iconUrl: "", brandColor: "" },
  { pubKey: "FwLsjPJdnSiuCvs1NXyR1cV6Sw5GRE6Lj2s1gZ9NNTmv", name: "CyberVillage", iconUrl: "", brandColor: "" },
  { pubKey: "6anBvYWGwkkZPAaPF6BmzF6LUPfP2HFVhQUAWckKH9LZ", name: "4BLOCK", iconUrl: "", brandColor: "" },
  { pubKey: "B6nDYYLc2iwYqY3zdmavMmU9GjUL2hf79MkufviM2bXv", name: "Mad Lads", iconUrl: "", brandColor: "" },
  { pubKey: "34mSDco9FM8599y4QF1GJvyWUrPixeT3zRNZAvzNXF6x", name: "Kolibrio", iconUrl: "", brandColor: "" },
  { pubKey: "i6PZjkPHGYmPfPE8LsJuLn5huZyusXhmysiDiHGPjxb", name: "MARVEL", iconUrl: "", brandColor: "" },
  { pubKey: "FACqsS19VScz8oo2YhdMg35EsAy6xsCZ9Y58eJXGv8QJ", name: "Lantern", iconUrl: "", brandColor: "" },
  { pubKey: "QhyTEHb5JkMBki8Lq1npsaixefUyMXWJtbxK6jNjxnn", name: "Black Sand", iconUrl: "", brandColor: "" },
  { pubKey: "57QggzHa8AEELBU3C8RG567oGmbG6VyoX5jsi6M3gaHp", name: "Beachside", iconUrl: "", brandColor: "" },
  { pubKey: "CV7uvPY1Hk5Avb2NvkGJoUzGnipZrEZK27j5rQJoUae9", name: "Theta", iconUrl: "", brandColor: "" },
  { pubKey: "2DNGsVZ9rg6RvT8bY4SGmGvyiVJ4xt9RL3NDd6uhfN46", name: "South", iconUrl: "", brandColor: "" },
  { pubKey: "3Xn3K5zeTzs4sURj1PCRaF6rvFg2hPgT49B4SiM998f7", name: "NuFi", iconUrl: "", brandColor: "" },
  { pubKey: "DzQHN1oTdN85Sbku2bc9Fu9yEwrgRMiu2XbRcntZ31yb", name: "Hyper", iconUrl: "", brandColor: "" },
  { pubKey: "Gvt8s5Bwnhg4G27VbnT1Zkfh7Jsztq6CNvZcc5anPonS", name: "Kevred", iconUrl: "", brandColor: "" },
  { pubKey: "9bb63m29Xy1KiWqijLs3f8adTE4KcSmVkt1qPxGkbkna", name: "Vault", iconUrl: "", brandColor: "" },
  { pubKey: "8yPiZWMNYMhEqTmPSRc6LsWLFC8pewYEzmgc5kRCLTrZ", name: "Limitless Systems", iconUrl: "", brandColor: "" },
  { pubKey: "AbacusTT3yhEFEKkQKjGStDhKDnvSFGpg9EqBwz8FnDF", name: "Abacus", iconUrl: "", brandColor: "" },
  { pubKey: "NeodymeDFipD7eA1ShrLJAZTBdHWcFsDB9YkoHshZNk", name: "Neodyme", iconUrl: "", brandColor: "" },
  { pubKey: "FnAPJkzf19s87sm24Qhv6bHZMZvZ43gjNUBRgjwXpD4v", name: "Pier Two Infrastructure", iconUrl: "", brandColor: "" },
  { pubKey: "SLNDoinxE7cCgE5ga6FJZ19F4FiUaEmtzSatbY6cjWy", name: "Solend", iconUrl: "", brandColor: "" },
  { pubKey: "6hcGvZypizjf6PPsxboshZHRqefyQKSG9L8vZqYdm7UY", name: "Onchain Divers", iconUrl: "", brandColor: "" },
  { pubKey: "GrefCNn5jSbcWv3uiervqZiCC87F8oX7PXz9LEBiog6s", name: "TruFin by Twinstake", iconUrl: "", brandColor: "" },
  { pubKey: "B1w6SZcyvjyp6zEyStcc8u9AxXAh2AbYvNzMmP9rRKE9", name: "Nordic Staking", iconUrl: "", brandColor: "" },
  { pubKey: "Ac1beBKixfNdrTAac7GRaTsJTxLyvgGvJjvy4qQfvyfc", name: "Stronghold", iconUrl: "", brandColor: "" },
  { pubKey: "3QPGLackJy5LKctYYoPGmA4P8ncyE197jdxr1zP2ho8K", name: "AndrewInUA", iconUrl: "", brandColor: "" },
  { pubKey: "76nwV8zz8tLz97SBRXH6uwHvgHXtqJDLQfF66jZhQ857", name: "Forbole", iconUrl: "", brandColor: "" },
  { pubKey: "MkyLHecSHN7TBdWgnh2J8KCsEHnsqqbVYSxtGmsshrk", name: "Michigan Blockchain", iconUrl: "", brandColor: "" },
  { pubKey: "1KXz4xKV2viJCGpxqnQqdf2J45vQr5USdmtcJLTaHkm", name: "1000X.sh", iconUrl: "", brandColor: "" },
  { pubKey: "7PmWxxiTneGteGxEYvzj5pGDVMQ4nuN9DfUypEXmaA8o", name: "Syncnode", iconUrl: "", brandColor: "" },
  { pubKey: "abc1zP7ihWsgQW8z5YmfQNqMckJE5Dfx8fwUNMNVNkY", name: "algo|stake", iconUrl: "", brandColor: "" },
  { pubKey: "GW8GgoeBpLM4TpeR2ePVcYYSoySBaKJgt2JiwoyjXRz3", name: "Luke", iconUrl: "", brandColor: "" },
  { pubKey: "GB44NXtM7zGm6QnzQjzHZcRKSswkJbox8aJsKiXGbFJr", name: "Rustiq Technology", iconUrl: "", brandColor: "" },
  { pubKey: "HLM6hyDWrEca9QMS92nDBa2AreU1qDkppttPVuJ7E2CU", name: "P-OPS Team", iconUrl: "", brandColor: "" },
  { pubKey: "4PL2ZFoZJHgkbZ54US4qNC58X69Fa1FKtY4CaVKeuQPg", name: "Block Parliament", iconUrl: "", brandColor: "" },
  { pubKey: "6hkfqeNAbURk7CmAQsP4Qm6WwHVF4LxHupEvQf7Tkrf1", name: "Valid Blocks", iconUrl: "", brandColor: "" },
  { pubKey: "STeaKrJdxdPMww27XJsjRBfrzqfjFT1BxotgQtFyDgx", name: "STEAK.NET", iconUrl: "", brandColor: "" },
  { pubKey: "4YykTGwg94GgHZEPSsQfbaMaEE9HHAHqSuXT65L6C6wf", name: "Rakurai", iconUrl: "", brandColor: "" },
  { pubKey: "644K33yWfSzc32VvY5fRUfUqphw8LTaLQntCkyEpJ8h7", name: "mrknc", iconUrl: "", brandColor: "" },
  { pubKey: "QWmexgr4teHa2ZF85tyf2hvEwBvJ6ioAEr1h8DRjoie", name: "Daiko", iconUrl: "", brandColor: "" },
  { pubKey: "SBLZib4npE7svxFA7AsD3ytdQAfYNb39c8zsU82AA2E", name: "SolBlaze", iconUrl: "", brandColor: "" },
  { pubKey: "Ehdn9LdjTAURQSMoDPERXLehtvzy7QD762wwPkzGT7RS", name: "SuperteamDE", iconUrl: "", brandColor: "" },
  { pubKey: "so1arJJbp9sis5XpovLyjTZPk8bDjfs37Meghi5wXbu", name: "Solar", iconUrl: "", brandColor: "" },
  { pubKey: "masvNDXtxVVMrYSV84RMry97JyHXAFcdfTZJ5VzpSYR", name: "MAS DeFi", iconUrl: "", brandColor: "" },
  { pubKey: "FahWJg2PkphJaMUUCzdYhXkD5NngUuuFRFD3YCE3BSwb", name: "Vault X", iconUrl: "", brandColor: "" },
  { pubKey: "GFXVa1g8zzAVDRnSuB6o9PnHuyH25ADvy2YJPZLpATuP", name: "GooseFX", iconUrl: "", brandColor: "" },
  { pubKey: "AY271jdvcyo5VzBiWsMGLEjpZFFrarq8FDydJHLmYgCG", name: "OranG3cluB", iconUrl: "", brandColor: "" },
  { pubKey: "StakeyJXE1yJbEApBVswHN4JdZXcj7V5MHbzffa4dFp", name: "Stake.org", iconUrl: "", brandColor: "" },
  { pubKey: "GNZ1PAAS33davY4Q1BMEpZEpVBtRtGvSpcTH5wYVkkVt", name: "Stakeconomy", iconUrl: "", brandColor: "" },
  { pubKey: "Fhks5gukimP6vxKYbRY4V1aw888EgHhpdDSscD9V6bub", name: "CryptoVik", iconUrl: "", brandColor: "" },
  { pubKey: "6hZL2FZim27WkQccMfygvvXH2eow5u3wR6XUJHbMoeWP", name: "Xandeum Labs", iconUrl: "", brandColor: "" },
  { pubKey: "vahVByZszdHguLa7U7GLz8UdUFN85mcwdkefiqVjtGt", name: "StakeITeasy", iconUrl: "", brandColor: "" },
  { pubKey: "cover89z945JotsCRGdbjakJm4rnL5XspFSPgN1mVZj", name: "Coverlet", iconUrl: "", brandColor: "" },
  { pubKey: "VALiDsfZKafvvQM5CMHhJd6PeVx9UpeDEC4Zk3WYikz", name: "Validators.link", iconUrl: "", brandColor: "" },
  { pubKey: "RaydiumJDX8X6om6Fg44xyqz5eukZ9KC3LX61SttLbH", name: "Raydium Validator", iconUrl: "", brandColor: "" },
  { pubKey: "57GUg9QH2LFMV11oaduuoqVJ5qHDEp7EGJ2xgkGiqAum", name: "anarcheuz", iconUrl: "", brandColor: "" },
  { pubKey: "9Gko8QZBbV5SrEvHKtQHcMrGGSfgFP3KJUozEGifu25x", name: "GateOmega | SolCircl.app", iconUrl: "", brandColor: "" },
  { pubKey: "FGtsnE1HB4bBi6g4xAt5mvWtuC3qBPWPBgWVrnRmUiVH", name: "Sunshine", iconUrl: "", brandColor: "" },
  { pubKey: "9KgZYnDzHhQANoJ43Z8czkgXYdTjtWLRrH9nDf42gqa", name: "Pacific Meta", iconUrl: "", brandColor: "" },
  { pubKey: "F3scMRjzSvXUa7JoK2uwBjNsYGi5sM84sDzE7FfGBo6o", name: "HAKUHODO KEY3", iconUrl: "", brandColor: "" },
  { pubKey: "magiCChVWbehZ1e3XqQfLh164yUfQ8LnRWgSP9i4oFp", name: "Magic Eden Validator", iconUrl: "", brandColor: "" },
  { pubKey: "adraBKLNY3DL3pg6SJRDYiMA8BsznaWpUdE42X41gbP", name: "Adrastea Validator", iconUrl: "", brandColor: "" },
  { pubKey: "3Z1N2Fkfha4ThNiRwN8RnU6U8dkFJ92DH2TFyLWJf8cj", name: "LumLabs", iconUrl: "", brandColor: "" },
  { pubKey: "NoRDTy8jpkpjPR7yxahVdoEUPngbojPhFU5jb8TtY4m", name: "Nordstar", iconUrl: "", brandColor: "" },
  { pubKey: "25quQGzrtcU224Kk7G5YDJ9oJXgYsiur8pZ7pAnCMhhV", name: "Komorebi", iconUrl: "", brandColor: "" },
  { pubKey: "53RJBy7aBGA7Aag6AryxEmBbsHDgwfBWagLrPbGHnfvR", name: "vladika", iconUrl: "", brandColor: "" },
  { pubKey: "Cer1umMkC6cvRGKKLP3QwxsdxsgxmC1EhqMhB1mqVvYZ", name: "CeriumXYZ", iconUrl: "", brandColor: "" },
  { pubKey: "77i1Ryv5bLp45yNeJCwCU28f37fGYspvRtGbNyxsD6Qe", name: "FREEZZ", iconUrl: "", brandColor: "" },
  { pubKey: "DSzLJLUQD55sxaCsJBHLFSV1SYngMmT7oY8rLpFhyGgb", name: "bloXroute US", iconUrl: "", brandColor: "" },
  { pubKey: "CwSZ17woioM2bqEbaswZJYvx5pemN6t3shBcU6zqPHyG", name: "Bandito Stake", iconUrl: "", brandColor: "" },
  { pubKey: "3VZHxnkK1A3HYeWYaqgMebHnc2acgLzRiXYwTNm3ooYM", name: "Orca", iconUrl: "", brandColor: "" },
  { pubKey: "FCvNkHa4U3yh7AXWGGL2jWLWiSRouR8EtzY5WVTHKTHa", name: "H2O Nodes", iconUrl: "", brandColor: "" },
  { pubKey: "91413b9eEvG6UofpSgwdUgH9Lz4QBF1G3J325Bw7JwGR", name: "Sign Labs", iconUrl: "", brandColor: "" },
  { pubKey: "86Sw9R6ynPmXnHfwUWinXtq1QoF2KHesfQQyZG5r8sXo", name: "Digital Energy", iconUrl: "", brandColor: "" },
  { pubKey: "D9BcS9Fasxj7zNv3kP5rHErv7aFxihi5EBZo9xUqaHeh", name: "Y8 Crypto", iconUrl: "", brandColor: "" },
  { pubKey: "SFund7s2YPS7iCu7W2TobbuQEpVEAv9ZU7zHKiN1Gow", name: "Staking Fund", iconUrl: "", brandColor: "" },
  { pubKey: "4tuMshQNpAFpy1YtEHnSsE5EPN1mAT8FevWvn2UPJHNM", name: "SOLGirl", iconUrl: "", brandColor: "" },
  { pubKey: "fdvtuDvWJZ89Z7TmeLjCwxgoLcmoEWNxruV48DvJtfm", name: "fd1.zip", iconUrl: "", brandColor: "" },
  { pubKey: "74y2qkCaJ5L17hTsz3E8jftNxTBCTvdz4P2L6qTHDW59", name: "0xNull", iconUrl: "", brandColor: "" },
  { pubKey: "2g2QU1NDRax6i2mKzRwgRfdBFoDkMC6bj7Zp5Q3i8sCq", name: "Grassets Tech", iconUrl: "", brandColor: "" },
  { pubKey: "Mxv1Ubm71XoUvxrN3qjN8ii6Bh5b43NuuKywsWx6ox2", name: "MX Validator", iconUrl: "", brandColor: "" },
  { pubKey: "JnGGar3XbAN6J3cKGRbNajCuhqnc9XWrk6WWr6hDmuM", name: "SolGuardian", iconUrl: "", brandColor: "" },
  { pubKey: "FzUNgBRnVxawDytN9GM7BFwxFfekuMs7BcAGybn4AmMk", name: "NTT DOCOMO GLOBAL", iconUrl: "", brandColor: "" },
  { pubKey: "9f7dqiYNBZbgPesAnLeWnKCtxYHSfMg5x1EMZCJwVwG7", name: "Prompt Logic", iconUrl: "", brandColor: "" },
  { pubKey: "Ebm1XKkMzaFg2L5rzLPBnFHMtpDPa6SWJ7nVUzZUmXmR", name: "Soldea Kitchen", iconUrl: "", brandColor: "" },
  { pubKey: "7tKWFaaLi2FJSqukHxUrnXph8M3ynrqn3kEkKPpgcNHZ", name: "Bitget Wallet", iconUrl: "", brandColor: "" },
  { pubKey: "SmithX2hngQMZXVN36C6TsyjthTU3YnsALAs1MaDghV", name: "Bluestone", iconUrl: "", brandColor: "" },
  { pubKey: "bay3rQMjiLPy6Nvi7tfNeVK26inBCxf88hKYyeKy64H", name: "Bay3", iconUrl: "", brandColor: "" },
  { pubKey: "AAAAQwH5KManM6mbxGLc1m1XnWcRBFDmdUgpZ4Ww621j", name: "11ama Validator", iconUrl: "", brandColor: "" },
  { pubKey: "uTnZDhnbiSV3TX2obj71nFPAm2aXy83mFTFYzaBRk34", name: "some name", iconUrl: "", brandColor: "" },
  { pubKey: "26RGqX3mezgYDxJnGh94gnMM4L2k9grH1eWcTSCHnaxR", name: "InfiniteSOL", iconUrl: "", brandColor: "" },
  { pubKey: "DPsW8v7gkGUbPPRnraS5e163bDepd9tD537X9S231T2j", name: "StudentSOL", iconUrl: "", brandColor: "" },
  { pubKey: "voEskim7SFWrPx1tV2PVisqyrJejxmDEARX11mtZ5vo", name: "polkachu.com", iconUrl: "", brandColor: "" },
  { pubKey: "pENgUh4K9zNacyU3PXVE9KugW98XCqZsWpEvA8d8wzX", name: "PENGU Validator", iconUrl: "", brandColor: "" },
  { pubKey: "8EVaZkBcoJAAyyRZfozNAnZiEopgPvnixx5Ja5PpVDae", name: "SoLove", iconUrl: "", brandColor: "" },
  { pubKey: "BDn3HiXMTym7ZQofWFxDb7ZGQX6GomQzJYKfytTAqd5g", name: "StakeCraft", iconUrl: "", brandColor: "" },
  { pubKey: "9tedbEYypEKXAMkHcg42rn3fXY1B8hB6cdE3ZTFouXLL", name: "stake.systems", iconUrl: "", brandColor: "" },
  { pubKey: "nebu1WnZBrFZz5X7sfPWuEqyb8LBSsrXpxaesnK9CRE", name: "Nebula Node", iconUrl: "", brandColor: "" },
  { pubKey: "mrgn2vsZ5EJ8YEfAMNPXmRux7th9cNfBasQ1JJvVwPn", name: "Project 0 Horizon", iconUrl: "", brandColor: "" },
  { pubKey: "C616NHpqpaiYpqVAv619QL73vEqKJs1mjsJLtAuCzMX6", name: "stakeware.xyz | ferric", iconUrl: "", brandColor: "" },
  { pubKey: "CiTYUYPAPHdcri5yEfsmqVcs54J6j8X1QaiFLgYqMVe", name: "Phase Stake", iconUrl: "", brandColor: "" },
  { pubKey: "4jEHuQZTNTRYAhxRYEjV3HJ1b4wqdQjnBRdPzFWzkCft", name: "Moise", iconUrl: "", brandColor: "" },
  { pubKey: "3iPuTgpWaaC6jYEY7kd993QBthGsQTK3yPCrNJyPMhCD", name: "ART3MIS.CLOUD", iconUrl: "", brandColor: "" },
  { pubKey: "jag77EXci8uf5uGmKE5izaYvxBCS5H9U2rxWYh8BUUf", name: "Jaguar", iconUrl: "", brandColor: "" },
  { pubKey: "9ymU1ayh9mZVyDL4dUUtXKtX1wCaFNzZPGutLJgqzuC1", name: "SunshineVR", iconUrl: "", brandColor: "" },
  { pubKey: "TRAMp1Z9EXyWQQNwNjjoNvVksMUHKioVU7ky61yNsEq", name: "Tramplin", iconUrl: "", brandColor: "" },
  { pubKey: "SWiz8fJt7CV99Uv9VZTLGAkMP3vTpc6u7ZqNN5dsWXU", name: "BOOP Wizard", iconUrl: "", brandColor: "" },
  { pubKey: "GMpKrAwQ9oa4sJqEYQezLr8Z2TUAU72tXD4iMyfoJjbh", name: "Moonlet", iconUrl: "", brandColor: "" },
  { pubKey: "686JcEJ98r8fMtUiVuKiz4WRoBpJ2Sm9zMhdc2b6H4bu", name: "A Unicorn Julia", iconUrl: "", brandColor: "" },
  { pubKey: "Cat8oWQiFfrR3c7BcceTYcpnYCzSWfCPjMXT7mfHXvEP", name: "HashKey Cloud", iconUrl: "", brandColor: "" },
  { pubKey: "dcntrKBwh8j5yL62Eg96Z5QjJWv3UXxMu4rqL82w6Cb", name: "Decentra", iconUrl: "", brandColor: "" },
  { pubKey: "PKvGYwh4efgythYddWAqGaPVuoZt8ybk7eXEoUqWxuA", name: "PK", iconUrl: "", brandColor: "" },
  { pubKey: "EpicsoqLdDP8qRn3wQRKTSKAXbjK9dUgFfNPRQS77MQD", name: "Epics DAO", iconUrl: "", brandColor: "" },
  { pubKey: "ENVaKoD7ytn58xJ8s5htFfQ8hqQt1G9dcPUDqbSwVcgB", name: "WEB34EVER", iconUrl: "", brandColor: "" },
  { pubKey: "sShosKd6uA5c1ZpVMxdsE6do13TLRWSMYsXbSMmNC77", name: "dogo validator", iconUrl: "", brandColor: "" },
  { pubKey: "2ayMCC4aizr8RGg5ptXYqu8uoxW1whNek1hE1zaAd58z", name: "Lifinity Protocol", iconUrl: "", brandColor: "" },
  { pubKey: "5CBkJdDPMWCmss3Y48B36w78Bgxur4mDib6tQ9yMKe1B", name: "TdrSys", iconUrl: "", brandColor: "" },
  { pubKey: "BrRf2kyJEuW8TgdeDjvJcKK4NzTzRtM9RB6WuVKXHxkN", name: "SPACE HIGH", iconUrl: "", brandColor: "" },
  { pubKey: "Luna8BkZNpZ9DKmszrZYPvFpTr4eJJfxxTnGDwTrYkv", name: "Luna Labs", iconUrl: "", brandColor: "" },
  { pubKey: "VaCdXKupamusfRsDf9Ai7e8Up36Z4f3MP6SqhnM7c76", name: "CyberAlex", iconUrl: "", brandColor: "" },
  { pubKey: "GakAanHMN4dYY8rMKL1e6uUKjNJj2nN2sENFaxzdMEBm", name: "4CRYPTO", iconUrl: "", brandColor: "" },
  { pubKey: "GK9MfwWEK7BvMS8eQDaiEPnKcqMJoS7SKUiEBQY2pfxC", name: "JDO Mainnet Validator", iconUrl: "", brandColor: "" },
  { pubKey: "gVot34jauJpexBL2YUSPBKsmZ4V2ffmDcRk4yfSEnx8", name: "Guardian Validator", iconUrl: "", brandColor: "" },
  { pubKey: "SQDSVTDfE5HqL7D6RjZk1vvZhaheWoskrDdDHCki68w", name: "Squads", iconUrl: "", brandColor: "" },
  { pubKey: "J6KaKtLRj7eQGuVVL2CAz1AS9kDxsrmej9QbYkEtsiAD", name: "DarkTower", iconUrl: "", brandColor: "" },
  { pubKey: "PineDoC593nrX16W8ZLWfF5Evb6otv7fRfZMLjPAHe3", name: "Pine Stake", iconUrl: "", brandColor: "" },
  { pubKey: "vanFfAkyFXFnj6TpmVwet6pJBnS4nBWNcJiE5GEsZ4K", name: "Quantix", iconUrl: "", brandColor: "" },
  { pubKey: "Hmq1oALENff8DejgYhJxB4njb6pyCtuMKKxotdZicB4n", name: "zim.one", iconUrl: "", brandColor: "" },
  { pubKey: "8zuMRTXThoPTTPLLvaiKiJshLLCqGMt9BdRjjCL19xBc", name: "DawnLabs", iconUrl: "", brandColor: "" },
  { pubKey: "Ec37CQZjwRgGnuMmUi3BnEBXS5Xa3siakAPxPkHtahSf", name: "Validation Cloud", iconUrl: "", brandColor: "" },
  { pubKey: "BSGMtRHy9qvsPbUKtT8yqd7nNqn2urTcSMVUgzj9zJVd", name: "Black Sea Gold", iconUrl: "", brandColor: "" },
  { pubKey: "6n8taYki7RscA1XW7xGmevLcqj855oSgDgjPe1dZyHfW", name: "Table Rock Jungle Lodge", iconUrl: "", brandColor: "" },
  { pubKey: "323d4ZiSqS1PwGwpJwD88jNPaGqkm7YYW2tJt2T8iFzo", name: "Chronoflare", iconUrl: "", brandColor: "" },
  { pubKey: "2wUhcnViyzstvWmk7NAboKtjbFbqJPo4BvFBV37dacLc", name: "StepByStep", iconUrl: "", brandColor: "" },
  { pubKey: "HcbE5huUVDgsf7SURsRfQqnFMp3Zz3i49eXMddugPyAP", name: "Solana Ukraine", iconUrl: "", brandColor: "" },
  { pubKey: "steakxfubt37xYdvuXz7BV5Uhhhk1FyJx9zGHfDcTVr", name: "Validator 1", iconUrl: "", brandColor: "" },
  { pubKey: "GdSJPrzj8q1QJV53s1cHMcpbPhodgB9kjG7X9kq8Z56r", name: "GXFC Validator", iconUrl: "", brandColor: "" },
  { pubKey: "5daP6pZoPSak6UEKuRg2HHjvTPpqqwB113oNamGNKuuZ", name: "Lumos Maxima", iconUrl: "", brandColor: "" },
  { pubKey: "5szskKdH8nfnUuHTvn9hnhH3Xuvo7RVmcDDvD5WD7yNh", name: "StakeNode777", iconUrl: "", brandColor: "" },
  { pubKey: "4MU64AyHBkRBUAYgAm91sP5vFgzUUgFHuS82CVhE8Q2Q", name: "Solid State Nodes", iconUrl: "", brandColor: "" },
  { pubKey: "sdo2QoiSsPknraeCts5GeBkV3AYDdtuxJ3VpYCS1CxR", name: "SkipLine", iconUrl: "", brandColor: "" },
  { pubKey: "5K8qgC9nHzKHSSyo9fKLsMfYmavYdMgEaYx86cMmVKVv", name: "Satellite Staking", iconUrl: "", brandColor: "" },
  { pubKey: "AuBB9st3RqhHBkzZgBSm6SVnHZNJQSHeBWCSkik4bzdA", name: "Latitude.sh", iconUrl: "", brandColor: "" },
  { pubKey: "BiRDEYE5K1dr6rQ6memx441BaZk8bYXzCwdShwgvLjtf", name: "Birdeye Plus", iconUrl: "", brandColor: "" },
  { pubKey: "3r5ZXC1yFqMmk8VwDdUJbEdPmZ8KZvEkzd5ThEYRetTk", name: "Vnode", iconUrl: "", brandColor: "" },
  { pubKey: "H9p8zGs56CnL4b7RrbwQ6htc6V4K8PUtKvqH2m7hYAtL", name: "nodtech", iconUrl: "", brandColor: "" },
  { pubKey: "EcjtYtuxBuupjeyXNdttATwoQoNL5Ck7bmrqDCj3ALT4", name: "johndoe", iconUrl: "", brandColor: "" },
  { pubKey: "GptPXjYUBUjxpRmueH6F5JcqizvjPTRDShTJQ8Vp6uN1", name: "maxfillipov", iconUrl: "", brandColor: "" },
  { pubKey: "34yvUa2fxfm2tUqxFEj9PHrVNwCcdzd51eo9hntWpZRs", name: "Aurora Validator", iconUrl: "", brandColor: "" },
  { pubKey: "H1kyn75BFTXr8QRmToRRvuEEmYan5n6M5APyfhMLau3b", name: "Wave", iconUrl: "", brandColor: "" },
  { pubKey: "42XzJdJvr1qE7zdEnPQhV5PsN9eyAcR45SWpTrifW1JB", name: "The Mandalorian", iconUrl: "", brandColor: "" },
  { pubKey: "4FsAxdHQ6HmFrDD7yCwsKNApuA67QYSCMoLAy3NfySxJ", name: "SunStake", iconUrl: "", brandColor: "" },
  { pubKey: "3jkJVgfz1zrHSy6YLK6g96eTj49kCnDj2i8AbbKLZhkk", name: "Node1", iconUrl: "", brandColor: "" },
  { pubKey: "5afRnmkFn1pRU9oussqwk1RRBVyoDgUkL16Jz4qNf574", name: "Staking kiwi validator", iconUrl: "", brandColor: "" },
  { pubKey: "bookLxG3LkSmt4htJ1x9zPw6E34RRMAi7sUn5mM3CNN", name: "The Library", iconUrl: "", brandColor: "" },
  { pubKey: "AYSvheimgwhpRHXossLqrTBDPwo4jHDQJ1UhMeAArTwH", name: "Dante", iconUrl: "", brandColor: "" },
  { pubKey: "4vqwZsEEEsKtSqqEWbLyFAciWg66jGLP9zrbcZ1Hsrxb", name: "Solstice", iconUrl: "", brandColor: "" },
  { pubKey: "hxVjzDmta9TuN1gM981TRKnfwG2uZ9TQDGwSCs3uDow", name: "Suzuko Stake", iconUrl: "", brandColor: "" },
  { pubKey: "7obieMdVPKKcwEhhKizSkpdLaW1HMZh2ENrUDUhdGvVr", name: "Golden Tower Staking", iconUrl: "", brandColor: "" },
  { pubKey: "6cvBCfFXugkTqgSFVPvzhoWaLbhHWvZfSsZadWP5rryR", name: "0node.io", iconUrl: "", brandColor: "" },
  { pubKey: "7Eg46UwGgsufXdd9C9kF27UAyD2t4VdmCdVTtPFoqxCy", name: "Bernardo Beacon", iconUrl: "", brandColor: "" },
  { pubKey: "dedxrPfNqPKBRmUyP9LDkaitpQzU6PD44jA6GP9Ndhk", name: "Ded Monkes", iconUrl: "", brandColor: "" },
  { pubKey: "3Qvmhayko5Yn3sSXDsHsMzS8QjdU4CshQF2y6L276kgi", name: "NastiK", iconUrl: "", brandColor: "" },
  { pubKey: "B8Jud6Mqv1FSKpjBM2hPBqoPhGMAciX2UqR9WcepDF7F", name: "Nodance", iconUrl: "", brandColor: "" },
  { pubKey: "Azc2uttGtHsRLorfQzd7tsMNtfaEg7LyvVEMVtckPCNN", name: "Fast Runner", iconUrl: "", brandColor: "" },
  { pubKey: "B1rsc6jv3RsFpkak8qvJN3PfGYSg9E3Uw1joaV1EoiFj", name: "RevTec", iconUrl: "", brandColor: "" },
  { pubKey: "2Y2opv8Kq8zFATg6ipqb2AjgCf18tkv1CLMLXQGif2NH", name: "Stake Shark", iconUrl: "", brandColor: "" },
  { pubKey: "9gANMngbGUmAaLXL1RC3JdiaLjRowJXNbzCTh53ht7mq", name: "Yurbason", iconUrl: "", brandColor: "" },
  { pubKey: "3R4effnUPr3sDo5wdegPBnqTmKTZhKkbgL1wxYw7w4B6", name: "Elysium", iconUrl: "", brandColor: "" },
  { pubKey: "2het6nBRLq9LLZER8fqUEk7j5pbLxq2mVGqSse2nS3tf", name: "MCF", iconUrl: "", brandColor: "" },
  { pubKey: "DfpdmTsSCBPxCDwZwgBMfjjV8mF8xHkGRcXP8dJBVmrq", name: "MonkeDAO", iconUrl: "", brandColor: "" },
  { pubKey: "7miZ2ZoXwS3YDzBRCbWcEtNVyuxk8WbbcyQwq7i5btvZ", name: "WestSide", iconUrl: "", brandColor: "" },
  { pubKey: "Node56Cr7y4Udym2vPt9DsRbWcBL29JivsGh2drpbKb", name: "Node Integration", iconUrl: "", brandColor: "" },
  { pubKey: "6oscGUEkXE8fyWoC4czRKbM1cuLkJNtgRsX1Un6w88Vf", name: "Vybe Validator", iconUrl: "", brandColor: "" },
  { pubKey: "qjUuLxWo29QCBr7ZQw4EPLkAtmjHS2ZdZpZcH9g7fRb", name: "Alien", iconUrl: "", brandColor: "" },
  { pubKey: "6D9w8FRw5EFr5qtZEphPpughN3W8zc8p6zMXg4PFuaXL", name: "STAKERY", iconUrl: "", brandColor: "" },
  { pubKey: "53ANFYA6BCDzdtiEeWawm5bqsH1Qgmjog8oMo5N4o4wU", name: "Zemnoi", iconUrl: "", brandColor: "" },
  { pubKey: "LunaFpQkZsZVJL2P2BUqNDJqyVYqrw9buQnjQtMLXdK", name: "LunaNova", iconUrl: "", brandColor: "" },
  { pubKey: "7K8DVxtNJGnMtUY1CQJT5jcs8sFGSZTDiG7kowvFpECh", name: "Hubra", iconUrl: "", brandColor: "" },
  { pubKey: "4QhNoG3PN1FXXFhAEA2QWdor6xjXvM9pjq6MXAUV8Zg2", name: "huglester", iconUrl: "", brandColor: "" },
  { pubKey: "fuyugZxM5S4NyV3ZYoc6ebs3fmRTrZ3X27MKCFvHpVD", name: "Kisetsu Stake", iconUrl: "", brandColor: "" },
  { pubKey: "21wUViiyG1g47VZ39ZZsSkFX9nu6bkyfy6jryHGD2TUB", name: "Easytoken.me", iconUrl: "", brandColor: "" },
  { pubKey: "LimeNKYH66uR9BwnrPtxPbpqmkambxHVcutGoSaWPiq", name: "LimeChain", iconUrl: "", brandColor: "" },
  { pubKey: "D3DfFvmLBKkX9JJNEpJRXpM1pYTVPQ5dpPQRc9F49xk4", name: "Easy 2 Stake", iconUrl: "", brandColor: "" },
  { pubKey: "D4mLBafAJjpRABT5Tyj6UhuwJ8DLRk74JzyuTMUdU9Fz", name: "AutoStake", iconUrl: "", brandColor: "" },
  { pubKey: "GZgVV7MMweKm11hh8z8Nui9kRo3VxUVr2qgmkDdtJesa", name: "GERSIA", iconUrl: "", brandColor: "" },
  { pubKey: "VNbW721iu6uVkrx246N2BiQth8u4b4SCPJwH3JvUovD", name: "Sarmina", iconUrl: "", brandColor: "" },
  { pubKey: "CHiaohVV2SQCFhiYP73iQzWT6HxnZqnAZJJqAYTeLAo", name: "The Chimpions", iconUrl: "", brandColor: "" },
  { pubKey: "sfo5vA1fFdPRsvqd8qdePtTnK97Qj6Jj3GupEzmNPjJ", name: "soltop.sh", iconUrl: "", brandColor: "" },
  { pubKey: "SWnetzxKaKtuysePKKAzdPAk3gqWgPYxg31vet69Xnz", name: "StakeWeight.net", iconUrl: "", brandColor: "" },
  { pubKey: "LunarE7WQyxpPwKo2hkEZZquu6UDWMNjvf3JyzGmdfp", name: "Luminal", iconUrl: "", brandColor: "" },
  { pubKey: "EGg6LTZDgV9CgpPZnpTTzmebSSyaH91cQ2eoiDxiJPvm", name: "MightyMooseValidator", iconUrl: "", brandColor: "" },
  { pubKey: "BiUSTKzDM57pkf52SqxqckEk4ap7d25y2GB4GLXxdgj7", name: "BurnItUp.com", iconUrl: "", brandColor: "" },
  { pubKey: "RLMS1xvot6R9RCDbCtZN8toXGm1ceJHXnBSNC1wY3FU", name: "Realms Validator", iconUrl: "", brandColor: "" },
  { pubKey: "ViKLknQuks11DLEjZ7Y2aNYAAT7Q3NTKLGxs8rdnLVi", name: "LightNode", iconUrl: "", brandColor: "" },
  { pubKey: "pt1LsjkNwqCKdYYfc35ToDkqtEG9pswLTJNaMo8inft", name: "ParaFi Technologies", iconUrl: "", brandColor: "" },
  { pubKey: "EUiPhYZ8NoWX5ZzDh2cRR1fAS4su9jjV3YE7veyactzd", name: "Marco Polo", iconUrl: "", brandColor: "" },
  { pubKey: "5frYQSynysBe1akCVK9tNBJ5j8jgBgUsjAXAgqHxvykJ", name: "Empyrial Validator", iconUrl: "", brandColor: "" },
  { pubKey: "2ZiMfQaT59j86HVWCvspuMtBotnVBeTc3BKk3kKpwgKP", name: "Stand With Ukraine", iconUrl: "", brandColor: "" },
  { pubKey: "CNcaYdqkCwxDpKSVK8in5f6kqrTiZ5SuHsHFDqx6jNvu", name: "Dual Validator", iconUrl: "", brandColor: "" },
  { pubKey: "DPhzpiNGU9C6576uLsNSHmdi2AxwxpjMsRdh2iVC4TPh", name: "SoLyrae", iconUrl: "", brandColor: "" },
  { pubKey: "b1uei1YN8YVb3qHy2JitBx4Fq9nAatLQFcNbnk6Ex8p", name: "Blue Sky", iconUrl: "", brandColor: "" },
  { pubKey: "RSSAw6n7Tvqi5iJc2xvHMfk1bhx47GVqj2pj1bq5NUq", name: "RSSA validator", iconUrl: "", brandColor: "" },
  { pubKey: "8D8XL6ovqx15RKwC1XtFyTz6H8JYF2fUsxTnsY4b123P", name: "STEALTH", iconUrl: "", brandColor: "" },
  { pubKey: "C8MLmDCg3LReWoNCkFdHgsscFpHx2WdtcU9ZziNfXrhd", name: "EvasMainnet", iconUrl: "", brandColor: "" },
  { pubKey: "eyeVhGmVEoPSWmQU2wP5WZmMihPBTCk7kMMm4VhuAKS", name: "Eyenotion", iconUrl: "", brandColor: "" },
  { pubKey: "A7uqmajxP3NdzbYDXiGQRGTL8d3dZ5pjS4kR9NTZcxtg", name: "L0vd", iconUrl: "", brandColor: "" },
  { pubKey: "noMiSdYbNQmFDrH2qMvYRXXzb5DUvjyPyDkXadzAPUV", name: "Nomis", iconUrl: "", brandColor: "" },
  { pubKey: "J1to3PQfXidUUhprQWgdKkQAMWPJAEqSJ7amkBDE9qhF", name: "BONK - Powered by Jito", iconUrl: "", brandColor: "" },
  { pubKey: "EfnywDKqArxK6N6FS9ctsuzNdxfx3pzfXEQE5EevQ1SV", name: "Project Super", iconUrl: "", brandColor: "" },
  { pubKey: "HdQ1Ap8wm6Mz65FaP8jMNBVfCDv5T9NdS8UTSvHmcotn", name: "Moutai Validator", iconUrl: "", brandColor: "" },
  { pubKey: "stsaYQJUhKZDHSqndGtgo6jgbhVaHBSHhtfVWxCwrhD", name: "South African Community Validator", iconUrl: "", brandColor: "" },
  { pubKey: "novaoLcuVHSudkW3Cphuhiv82vspN5qzinGCtEbwQxz", name: "Nova Consortium", iconUrl: "", brandColor: "" },
  { pubKey: "HwcVgFSgmfeeF7zGFUBLoVA8Hpx8rtwyfCrJ1npBaSVC", name: "Solya", iconUrl: "", brandColor: "" },
  { pubKey: "HMk1qny4fvMnajErxjXG5kT89JKV4cx1PKa9zhQBF9ib", name: "BLOCKSIZE", iconUrl: "", brandColor: "" },
  { pubKey: "mesh3Px7WMi7Dkxke4ZZBULoKHM6sp37wKtg4DwPqPY", name: "Mesh Validator", iconUrl: "", brandColor: "" },
  { pubKey: "QXmsTYFK7YT2BpP2AnvXwuRpfwmsJZpovLcUqdSjoK1", name: "Honeybee", iconUrl: "", brandColor: "" },
  { pubKey: "mNyQrNRYAuL2CwNCGmCsmwj9EcG88Sf8hs5rCirZaUr", name: "WinStake Labs", iconUrl: "", brandColor: "" },
  { pubKey: "GzjMbJQDVuBLFY69QwhhjDGDy2o5Q6nswXMuVTCWEFnp", name: "Omakase", iconUrl: "", brandColor: "" },
  { pubKey: "axyQeKp44XqUnvC1jVHoeuAJ3j8wVnGeWtddeAcNYcF", name: "Somos Validator", iconUrl: "", brandColor: "" },
  { pubKey: "4EsJD6cpaae8rh27U9pHsfxAheCLQnze1bDvXZfpjcUv", name: "xSTAKE", iconUrl: "", brandColor: "" },
  { pubKey: "76DafWkJ6pGK2hoD41HjrM4xTBhfKqrDYDazv13n5ir1", name: "Solana Japan Validator", iconUrl: "", brandColor: "" },
  { pubKey: "Hx4UJCvf8amGeuW9fPFfTckRoznDHxPSYiU9HuUSZKLT", name: "Kairos Research X Firstset", iconUrl: "", brandColor: "" },
  { pubKey: "votem3UdGx5xWFbY9EFbyZ1X2pBuswfR5yd2oB3JAaj", name: "Ice Staking", iconUrl: "", brandColor: "" },
  { pubKey: "5cYwwC8dmQ2tvtjDueHrU2B6NvmTHmoimsNGeGXVbkP8", name: "NeuralNode", iconUrl: "", brandColor: "" },
  { pubKey: "8vyuJTHSDkx7k1zymea4TMsgvixf3rCYBXHPDQajePkE", name: "LuSOL", iconUrl: "", brandColor: "" },
  { pubKey: "LNRmxHyXAzgBkgxDmb4ZefwLAnSv3fdsjPgjmThoa1T", name: "Banana Business (BB)", iconUrl: "", brandColor: "" },
  { pubKey: "DG6fVEB2Qy1jntvHVPui3R12CMqcwNNnjYPYdsbQ9ACP", name: "ILY Validator", iconUrl: "", brandColor: "" },
  { pubKey: "4m1PbxzwLdUnEwog3T9UKxgjktgriHgE1CfAhMqDw7Xx", name: "Kuma Validator", iconUrl: "", brandColor: "" },
  { pubKey: "ExYX8UKQTCf2VPtV9jbfqikeTV6tPfhzauJ896o91wtj", name: "LEVMA", iconUrl: "", brandColor: "" },
  { pubKey: "goJiRADNdmfnJ4iWEyft7KaYMPTVsRba2Ee1akDEBXb", name: "Gojira", iconUrl: "", brandColor: "" },
  { pubKey: "4udPrmxccbP1NwDJ6vChFKs5qcqyjmQff6gsKXD1mdaj", name: "00Tokyo", iconUrl: "", brandColor: "" },
  { pubKey: "6AAeoHYMUQfSdFGqubUmWVAasFkzJEq47oKpHNNTZxLN", name: "Tane", iconUrl: "", brandColor: "" },
  { pubKey: "5BAi9YGCipHq4ZcXuen5vagRQqRTVTRszXNqBZC6uBPZ", name: "0base.vc", iconUrl: "", brandColor: "" },
  { pubKey: "2QE9X9X4tdDUTYic1DgBBJjU7cWUNPbKYGerCb9KqDQN", name: "val37", iconUrl: "", brandColor: "" },
  { pubKey: "5RCD4pZcKH3NHN4XHxvsnVAawSaConLgsZbreSN5dXpZ", name: "NeNa", iconUrl: "", brandColor: "" },
  { pubKey: "ACCRENAtboR1MyyoiPvwNZNkjt1GcLARrACh6hZXdddF", name: "Accretion", iconUrl: "", brandColor: "" },
  { pubKey: "roYL9AoyuGae7uEAErzZhPSSxnLLZU4TNx8wmwCk77r", name: "Royal", iconUrl: "", brandColor: "" },
  { pubKey: "CzmqDuqEpfnkptuLAcikmJrhCnhFXo8aUBj6Rto1SPAc", name: "MARGUS.ONE", iconUrl: "", brandColor: "" },
  { pubKey: "GdVBPczdFaPf1GXvx8ByHeA1ZHAHwwmdQEPihH74SXm9", name: "rossi-mainnet", iconUrl: "", brandColor: "" },
  { pubKey: "dstqVmt3cDH43Ux2SeTY2Hza1eVW6pwGLwehWCLfuPd", name: "Dust Eleven", iconUrl: "", brandColor: "" },
  { pubKey: "hnhxfrndd827LET6jvnQV4aWqpS2EedaHcT4gj8ArSu", name: "Hodl & Hodl LLLP", iconUrl: "", brandColor: "" },
  { pubKey: "8mu3JHHF1Qkcrbqjo6KWxyWvTxarZjqptJTokR2jrDFo", name: "Mira Validator", iconUrl: "", brandColor: "" },
  { pubKey: "o27rnqfNHPwHsRp2xPXXwWzn2q2dGxn6UD4Rt5KMU5h", name: "Stake.Cake", iconUrl: "", brandColor: "" },
  { pubKey: "nateBZg7oHVPLB2samBLkKvfzedU3ALZBexMFPMKjn1", name: "Epoch.Day", iconUrl: "", brandColor: "" },
  { pubKey: "jntrMCSkeNagaMM437fhZxLYbFJh6pvj68bQDZx2pXf", name: "Janitor", iconUrl: "", brandColor: "" },
  { pubKey: "1i1yax3thZfiV8id5HTA61bjsxEi4pbjmhXsqy6JePP", name: "Lilith", iconUrl: "", brandColor: "" },
  { pubKey: "STevE9xVb1QfBHU4GgEn28r9oikAf5yxKJddF7fufwb", name: "STEVE", iconUrl: "", brandColor: "" },
  { pubKey: "DCKYVqFDwUs5m2DhW9muK2EX86pootvWD8wXA4nSqDxU", name: "Dicky", iconUrl: "", brandColor: "" },
  { pubKey: "xLabsqDpN9WHXEXSJXk1yhqh5H8BgcqiBP1CR6Mkjcb", name: "xLabs", iconUrl: "", brandColor: "" },
  { pubKey: "chdv8H9fPfk2zFqSVaxRjsEo2qEDmswbju3BVgAHPNb", name: "CH Dev", iconUrl: "", brandColor: "" },
  { pubKey: "PoNV8asqSrjTr9vBBW4Y7f5PVWUCzUXByz2AqcTzv1j", name: "Ponke Validator", iconUrl: "", brandColor: "" },
  { pubKey: "EJ59wFK3qPrnsFFSpZ7jSwCnXe8hVQ12heXYUqry7Muc", name: "Crypto Plant", iconUrl: "", brandColor: "" },
  { pubKey: "7X7oVv6K6wawMNzVriczSAEk18GzqyrYrvqyJbwLAY3s", name: "LuminaNodes", iconUrl: "", brandColor: "" },
  { pubKey: "9QFvZhLvpbcFJTPkKq5wTWR2DGTXqrsP8z9igPgjSsZ1", name: "StakeChain", iconUrl: "", brandColor: "" },
  { pubKey: "EnRcbgr5r7EUS2P35szncy6TW6eWA9UQiU3yQRCDbh2P", name: "Sec3", iconUrl: "", brandColor: "" },
  { pubKey: "BmMVRAVef2qmJ1tJpG3JwRUtnfEiTbvDw9ZeFEi4wE7D", name: "Stakely", iconUrl: "", brandColor: "" },
  { pubKey: "gfR2VCrsVcm1gF2teasQpP6BdX99mVVFhEQck3UhTNC", name: "Next Finance Tech", iconUrl: "", brandColor: "" },
  { pubKey: "ChaosDKeBjU22B4nnvYWXyTRPuWTzJBR4m3QPfBw6Tta", name: "Udder Chaos", iconUrl: "", brandColor: "" },
  { pubKey: "sagasJDjjAHND4hien3bbo5xXkzCT5Ss6nKjyUJ45aw", name: "Saga DAO", iconUrl: "", brandColor: "" },
  { pubKey: "5XGMWvqZSBk1fktPtxbwaMF5dhkbrtchpwd4xiXG9q8u", name: "Nam-dok-mai", iconUrl: "", brandColor: "" },
  { pubKey: "4269foF8CYyT8SynFSYHiKFzHva5YL6PoAQj9pH3mQmh", name: "Mice Stakin'", iconUrl: "", brandColor: "" },
  { pubKey: "AnodeNCzJGQ7QwheFqJr6EknKGa72m6XHiLtDQiXcmEc", name: "Anode", iconUrl: "", brandColor: "" },
  { pubKey: "chrtyiAw8suFRvS7rTcfgcDyNu49bGPNZ2fjSPzNPFr", name: "Charity Soul", iconUrl: "", brandColor: "" },
  { pubKey: "4qvFxnUXYjBdcviCwVV7gKcGJMCENEBfS82hSLJUhyvu", name: "DICS - Degen Infrastructure Core Services", iconUrl: "", brandColor: "" },
  { pubKey: "GuxBSrv5jnSwwPepkqnmkM7YCBSakKanbnw4BKMdda4j", name: "SGTstake", iconUrl: "", brandColor: "" },
  { pubKey: "SPHEREcukWjz5VUiGU7Kh3fWeN4neyNw1ma2qQHXmrH", name: "Sphere", iconUrl: "", brandColor: "" },
  { pubKey: "HAYEKSWg2EY21k38St9X5yM7QMW6SunKDefs5SqYSFty", name: "Hayek", iconUrl: "", brandColor: "" },
  { pubKey: "BLX5PkLh7GsHaqCpLDxiW3UjxfT2GMyteVAhRZBYhCts", name: "KitBull", iconUrl: "", brandColor: "" },
  { pubKey: "EogKVYgic8LKAuV1kR9nRqJaS5zpwCvSMfqoehzmAMpK", name: "Chorus One Research", iconUrl: "", brandColor: "" },
  { pubKey: "4DW4nrbGrjXRhhj3CH3AYgocExfqEoCCSMxZ9uzc3NpK", name: "Irishka", iconUrl: "", brandColor: "" },
  { pubKey: "mythxna3hpzXSbaseyR12vu5Vvym1HxS92eCgXLvY7w", name: "Mythx", iconUrl: "", brandColor: "" },
  { pubKey: "3pBPy27F1Wz3iVydZnGkdvefStrFm8UMCDakYZii8AUZ", name: "NodT", iconUrl: "", brandColor: "" },
  { pubKey: "NikGQUQqSLtsdHGGx7mQopojZcgd3N9uWFaZQ1r5EXn", name: "NCValidator", iconUrl: "", brandColor: "" },
  { pubKey: "eUkPmbsMwxMFr8v1m6sBYJ9MoZ2LpbiHNHWeZiGpFHp", name: "Teraswitch", iconUrl: "", brandColor: "" },
  { pubKey: "3a2onvgTpGynakAQwx6gigtSeL7itZewNxqb5JiAvWeA", name: "STAKR.space", iconUrl: "", brandColor: "" },
  { pubKey: "7HhmcAGzjChFjG1qsN4Y9NPgDWfytXXVA7ZRBWE7eZc3", name: "O'Solemio", iconUrl: "", brandColor: "" },
  { pubKey: "Dcoj98wWiKhA4iqxcSg7NtuR2miA7tZqtycMdkPo8XDw", name: "PADDY", iconUrl: "", brandColor: "" },
  { pubKey: "8B2Z2R8dRvqFcXuLBwinu3Jq7HQidCaJCnDuRRqeJLC1", name: "Watatsumi Validator", iconUrl: "", brandColor: "" },
  { pubKey: "89DXJe6XTDASsmyXJoPyRetLq1csRj9N2Bwn67fNvYGt", name: "Blossom", iconUrl: "", brandColor: "" },
  { pubKey: "H6rbcwuQtadcv9JvxLM7GEskF6xFXnrNT3iPkk4RfyBE", name: "LootGo", iconUrl: "", brandColor: "" },
  { pubKey: "H4QVPxS7napq3NEYxqLhxbKi9nJ8s56dD2EQZGsyZ3sb", name: "T-STAKE Systems", iconUrl: "", brandColor: "" },
  { pubKey: "CP6mfD4Qc5AYrboXBAQeHMYj5x1UnYksDXRjG7DMkHH7", name: "Dragon Trust Stake", iconUrl: "", brandColor: "" },
  { pubKey: "F1wBgGku883aGGCQYMQFR4PmdJ7faej3qKSk8xGCycP7", name: "SelfLiquidity", iconUrl: "", brandColor: "" },
  { pubKey: "EJHf5N9is5spAF5Kz384tTvTV3CwTka6qzUoZrYm53SV", name: "Windfall", iconUrl: "", brandColor: "" },
  { pubKey: "sTach38ebT8jnGH8i2D1g8NDAS6An19whVMnSSWPXt4", name: "Stache Node", iconUrl: "", brandColor: "" },
  { pubKey: "DvFTFLrEQSfEadPQdesvf5bpYWYqXK9iaJAjq95piQBs", name: "Unit 261", iconUrl: "", brandColor: "" },
  { pubKey: "GEM1N1pCDGKiTa547eckcwuHWYMsUQeXgnXHfEZLDvpB", name: "Gemini", iconUrl: "", brandColor: "" },
  { pubKey: "BSRRvjdKd8SHApi3KtTGbzrdhUojitiwAt4xt4nAxbFh", name: "Green House Crypto", iconUrl: "", brandColor: "" },
  { pubKey: "SoLiDDVm88uWUMk2rQpG7B9wC55a6xveYEz3JnS6tzC", name: "Solana ID", iconUrl: "", brandColor: "" },
  { pubKey: "BdM7KCd6ZYWcaCMmHVi8YeL4jFzDVM9cRLJUeRAGSvMS", name: "myhauz", iconUrl: "", brandColor: "" },
  { pubKey: "GaxxAn5335dA4U3772MCFeqdyqCVEfmsQTQ47YXfC2Xi", name: "Gaxx Validator", iconUrl: "", brandColor: "" },
  { pubKey: "4BVYjw1ztUzUPsxsaCheWWwThT2X4rjogZytGnuWPUGg", name: "SOLrainDrops", iconUrl: "", brandColor: "" },
  { pubKey: "odc2aCE7yWTcV8ApP1cHmVqQZTkLNduqaYyKE1XhpE3", name: "Odyssey", iconUrl: "", brandColor: "" },
  { pubKey: "pine9rHVDS1pjwdhYkx3vRyaAyRd5KPDKXZEXAqvxcX", name: "Pine Analytics", iconUrl: "", brandColor: "" },
  { pubKey: "A9jRCzF4uxLVnVs8ihQECtZ5ZMbHUvoZusddxTQ1iRQc", name: "Nodz", iconUrl: "", brandColor: "" },
  { pubKey: "7zKQnt19j7aZ1YjzBk6UUUdr5dGb65A36kW1TYAbB6b7", name: "TIEXO", iconUrl: "", brandColor: "" },
  { pubKey: "9NZ18GkTnXZug6eXAzpBsmyCsYfAJ7mL9bgUfSJDSAKr", name: "crypto-jack-sparrow", iconUrl: "", brandColor: "" },
  { pubKey: "FH9xcL7Fqkreq1wSkn2Vf7AfnMEyo2KK7QX32LTFndt6", name: "Fountainhead", iconUrl: "", brandColor: "" },
  { pubKey: "SANDhe6azby4EMLJd8N77QTk5K92n2tCi4NXba7iwuc", name: "Goldsand", iconUrl: "", brandColor: "" },
  { pubKey: "Ay5AcULBRJznGEEaGm2mWziRbefETRjdfZ1kwsoXS9u", name: "BTHS Student Validator", iconUrl: "", brandColor: "" },
  { pubKey: "CtzNnqzSLwNtkzi2yEWvq4w3GYQ5gSpCagqFZ5TbdSKb", name: "Citizen Node", iconUrl: "", brandColor: "" },
  { pubKey: "DHoZJqvvMGvAXw85Lmsob7YwQzFVisYg8HY4rt5BAj6M", name: "coyote.staking", iconUrl: "", brandColor: "" },
  { pubKey: "mALLoAbdQrgsnm7kWJyPrhcQcmxfT73t8DaqEkpZNd6", name: "mallow", iconUrl: "", brandColor: "" },
  { pubKey: "YE111yizdzBA7JQKMXjy9VSx1shKAczUbs3b3e6vKQH", name: "Mellow Yellow", iconUrl: "", brandColor: "" },
  { pubKey: "7JZTyHRTmzHfmHH89uT9xKSKDVJ1VnNQ1FeTeM4iH3J2", name: "Shiro", iconUrl: "", brandColor: "" },
  { pubKey: "1LinkCP4qUqGvUiNuAWhAxQyopdBxsh4vhfLBb4apyR", name: "OneLink Solutions", iconUrl: "", brandColor: "" },
  { pubKey: "wetwJSUHT5afX3gP49q75gkz8FcCfvsw2kuSQ1UjT9R", name: "GUIDES", iconUrl: "", brandColor: "" },
  { pubKey: "AfyTzhTXBRBCxGdTEMc9LNEkVGVGfGA9wHf1VikaNb37", name: "Fthr Validator", iconUrl: "", brandColor: "" },
  { pubKey: "8sdFdnuKsY5KvpEU7gPi7qH1fP5DdYWfDhiF7NLjtaX8", name: "Chainflow Experimental", iconUrl: "", brandColor: "" },
  { pubKey: "8xV77wuFP5BkMDdb1845hRRWZNbDNAbcV75BjMuViWpf", name: "StakeThat", iconUrl: "", brandColor: "" },
  { pubKey: "gGQb6ZcDG7fsVLWTvXZ1LLoY348tc1zcP2wkh8kshrk", name: "Waterloo Blockchain", iconUrl: "", brandColor: "" },
  { pubKey: "DyDjFYB6i51FMHQvB4eKSwGHmgMxVf1i3FWwANAngqyY", name: "CuBe-M", iconUrl: "", brandColor: "" },
  { pubKey: "prt1s9dMM15LdsUX9HugajzqPB5WVN8a2mw3frAiCfj", name: "Portals", iconUrl: "", brandColor: "" },
  { pubKey: "irKsY8c3sQur1XaYuQ811hzsEQJ5Hq3Yu3AAoXYnp8W", name: "Solana.capital", iconUrl: "", brandColor: "" },
  { pubKey: "4KfAqBj3Jvi9GGngFK1MbZkjHTcSFyvhFnVwc2QrNiEh", name: "SolLana", iconUrl: "", brandColor: "" },
  { pubKey: "FSDKGroWxgBf7VmV6X1NLDhnncrWW2ekztwRWiJrPf3k", name: "To The Stars", iconUrl: "", brandColor: "" },
  { pubKey: "ySxF6XaSFSwU46iJbgyh2rAW5jagLbYULPtWvZCshrk", name: "Blockchain at Emory", iconUrl: "", brandColor: "" },
  { pubKey: "9FZWpUMfXZ3993g2BfqSFg7xcx9iUCxQwKeYzr2WQCM1", name: "Solarius", iconUrl: "", brandColor: "" },
  { pubKey: "1eufsJbqNgMProke17FLSw7JrD97fYhGggrnH9zyWnG", name: "Piranha", iconUrl: "", brandColor: "" },
  { pubKey: "6hTLQ5HSdWcpZkbXmZxXaGjCgTh7zh8UeWKWKgGE1BPp", name: "6hTLQ5HSdWcpZkbXmZxXaGjCgTh7zh8UeWKWKgGE1BPp", iconUrl: "", brandColor: "" },
  { pubKey: "9DR48EtgDzh3Gx5HiiQikZn9c2y12casm1bcUMuurV2x", name: "DriveSol", iconUrl: "", brandColor: "" },
  { pubKey: "G1juWDqojmp5CWDhgRqtXrtpAFw9xqhjmEQAKr9faf4V", name: "Huisky Staking | sol to ", iconUrl: "", brandColor: "" },
  { pubKey: "LTPVqpXFDkXh1e8afTkX5RkxyGkM198TcEUYAq7bUrK", name: "LTP", iconUrl: "", brandColor: "" },
  { pubKey: "94EhHE7MaKHq4p8oFADeyizDjwYwgFn1YBYGky8mR35z", name: "[NODERS]", iconUrl: "", brandColor: "" },
  { pubKey: "STPTPuWoyKzbWawom5DBndxkeRFAjW4PzJ2EjL1qeMW", name: "Solana Portugal", iconUrl: "", brandColor: "" },
  { pubKey: "THEVb5dS9gHYnr8eu2FHCprjnyp3uqmHNofUXD8MCQp", name: "Theia", iconUrl: "", brandColor: "" },
  { pubKey: "ABREUtpzkkMiPHrBebpsYDU3mubtSohjDKZbyRoTJLae", name: "ABREU Foundation", iconUrl: "", brandColor: "" },
  { pubKey: "5DnWqsJceNamPNNUpMnVr1XQ8anSxcj9TXRD5Rn52prJ", name: "TopReward", iconUrl: "", brandColor: "" },
  { pubKey: "ELE2xaC6i6pmeu7bfrYjBv4whBeTAbgwcg5hf2ythiBs", name: "Fundamental", iconUrl: "", brandColor: "" },
  { pubKey: "FLCrbfbwEhFARa8nK9rnZw8BVtKNAuHujh9EhWy5A4U4", name: "SolanaBull", iconUrl: "", brandColor: "" },
  { pubKey: "BARLL1NvF3jPHQ3zb82q1v5m6uewcpkgRBYVNufQMWjo", name: "Swyke | ISO27001", iconUrl: "", brandColor: "" },
  { pubKey: "D7WodK26tETSqyWBW35vvMGfige9afLEyTsm1Pvvropd", name: "Litx", iconUrl: "", brandColor: "" },
  { pubKey: "vvvvXsU6iG2enDVvs4KeVqS4YrZczTujSv5p3dSeNHx", name: "Pesky Penguins", iconUrl: "", brandColor: "" },
  { pubKey: "5eJQDSbgTZSEmH3zSWDEdAKgjavUUn9BkouCFNLz1x93", name: "Ivy Oracle", iconUrl: "", brandColor: "" },
  { pubKey: "adrePWHJJQNNuMfK3QrBKXDZZuRFPRjhovMMeSr3Drz", name: "Adrena", iconUrl: "", brandColor: "" },
  { pubKey: "TKMA1fBGq4M7gF2CNnhphX6vNateFc2cm2FL2mYwq7e", name: "Tokamai", iconUrl: "", brandColor: "" },
  { pubKey: "Defi89YpAhk3Gst1Jpsi3Nhj7yCu5HropESh37SQ2v9g", name: "Yield Lab", iconUrl: "", brandColor: "" },
  { pubKey: "9rwCwfL74J6AfgKbVK7s7jjMqngvHtiBcV1WTNXN8hLa", name: "Solana Vibe Station", iconUrl: "", brandColor: "" },
  { pubKey: "Gotas1PRPrkqqSNm1ZKcn8Tpx9qL8krSQzTZ5DPKzkFX", name: "Gotas", iconUrl: "", brandColor: "" },
  { pubKey: "FgiteGaHbA22Wt4Quzv3muscQtvX7gzVwvUHbFnb3rTJ", name: "SUNREN", iconUrl: "", brandColor: "" },
  { pubKey: "DKeL7T5t7XXKSbWpM3i9mkV9hRhqrEDbVVyL63AJ7TqE", name: "Solary", iconUrl: "", brandColor: "" },
  { pubKey: "fVotEjqpmpQYgyVyBCwYm62BKqqTQNE6SpYnRmdBazH", name: "_gamma", iconUrl: "", brandColor: "" },
  { pubKey: "ExCHgw3CfdZTbsrDA2phe95jswV2bDr5oSJwyKJKzEdN", name: "Exchange Art Validator", iconUrl: "", brandColor: "" },
  { pubKey: "CarbnAxSfvsBdp6otKtoUa8XmUaX9PcsGq6R2WqZMuw2", name: "Cloak", iconUrl: "", brandColor: "" },
  { pubKey: "6BUqzA7GtQJ3qZXHrViMSGFdXNvrbcD56Png1mNRqGN6", name: "Selex Validator", iconUrl: "", brandColor: "" },
  { pubKey: "DeEpSdaw8uBLQ5T2HQhDf8fBSVbm13jGqJwoSF3HTpL5", name: "DeepStake", iconUrl: "", brandColor: "" },
  { pubKey: "33JxTD3GkHU8zePNVNjJwEM9BFChWtzPdGFMwL4Ar6X7", name: "Amber", iconUrl: "", brandColor: "" },
  { pubKey: "vnd1jskPHR2gfMtgTtq6xCwANrAiNbQTKgVBAJHnMke", name: "Vandal", iconUrl: "", brandColor: "" },
  { pubKey: "LodezVTbz3v5GK6oULfWNFfcs7D4rtMZQkmRjnh65gq", name: "The Lode (Sentries)", iconUrl: "", brandColor: "" },
  { pubKey: "kyvvvkDpDCtSxQMPhzRhmv14DgUBVEGGzn8Dnb8ircP", name: "Kyzzen", iconUrl: "", brandColor: "" },
  { pubKey: "gangtRyGPTvYWb8K3xS2feJQaCks4iJ7rytFUPtVqSY", name: "The Lotus Validator", iconUrl: "", brandColor: "" },
  { pubKey: "FH5SX1WUubW9nD1rweZMofCHGhEp8qUMx3PksLfshrk", name: "Rutgers Blockchain", iconUrl: "", brandColor: "" },
  { pubKey: "GLB3jUr5zuu79zFuEH3KP7boxtWsjHVyYRBK2SPshrk", name: "Blockchain at Georgia Tech", iconUrl: "", brandColor: "" },
  { pubKey: "FRqYRkp3tUoBc62pnabeX8SVr6p3v6HM2tzT2NVshrk", name: "Blockchain at Columbia", iconUrl: "", brandColor: "" },
  { pubKey: "c3wFuF1LCtsY5DGo7eBQCwLHhtZgAxNwNDrUCqashrk", name: "Villanova Crypto Club", iconUrl: "", brandColor: "" },
  { pubKey: "Cw2b2ng2fa78ndCXHcJMT1pqvdGxUHu5EBEB8KBshrk", name: "University of Minnesota Blockchain Club", iconUrl: "", brandColor: "" },
  { pubKey: "ksQuu3JAStVXUeDCHeW6QtVRHNMcdtgPyepUd3Yshrk", name: "Princeton Blockchain", iconUrl: "", brandColor: "" },
  { pubKey: "T6bpj6H6fr9GyKe73DcNjPbGeSk8twDsiNcU4srshrk", name: "Dalhousie Blockchain Society", iconUrl: "", brandColor: "" },
  { pubKey: "DMPhNJFSvi34NmfcqR4B5rdKgDYY3kZbXpdXJBL4cJ1q", name: "Flipside", iconUrl: "", brandColor: "" },
  { pubKey: "SzNm2zDpK3eJmSYR21pRaQ5b4wQ37ecds6det5YCZFP", name: "SolX +Mev", iconUrl: "", brandColor: "" },
  { pubKey: "BH7asDZbKkTmT3UWiNfmMVRgQEEpXoVThGPmQfgWwDhg", name: "01node", iconUrl: "", brandColor: "" },
  { pubKey: "4Q1khZnsdtNyQjUCpYPBDYyogui8b9x1MWtKNdaPiJdv", name: "3SDK", iconUrl: "", brandColor: "" },
  { pubKey: "FoXyNdpkiQBsWgrYER43PcZ5rcpzMk8jGxN3NyEx5dmB", name: "Famous Foxes", iconUrl: "", brandColor: "" },
  { pubKey: "te1exfYnykh2cFGCwGSLQu26Dpr8n2PozvBqH5Eoi3K", name: "Telemetry", iconUrl: "", brandColor: "" },
  { pubKey: "Fe5zMqkmoYbwnXH9RHjFy7YMRnak9so2bzPBroPJ4iiX", name: "U1S1 Validator", iconUrl: "", brandColor: "" },
  { pubKey: "ZoDVQ5zCgFyVm2Y6vHhZ6boQEZNV6sMVnefev4M2Bes", name: "Zodia Custody", iconUrl: "", brandColor: "" },
  { pubKey: "BeRtYZ7SVQozwTby6ajQzrHtKYkn4qoKyRfb3NDAedtA", name: "BIG BERTY", iconUrl: "", brandColor: "" },
  { pubKey: "rFLcT89WTT6kJsKmrMzpz5FUZHy7Z9bycBF1Q1SMy6i", name: "Reflect Validator", iconUrl: "", brandColor: "" },
  { pubKey: "unRgBLTLNXdBmenHXNPAg3AMn3KWcV3Mk4eoZBmTrdk", name: "Unruggable", iconUrl: "", brandColor: "" },
  { pubKey: "4RcSXeQbgG1v27M27PNNLhy9PGB6uaJACXUZ3kBVc4kF", name: "Spark Node", iconUrl: "", brandColor: "" },
  { pubKey: "5DutFKQ8qPmbjFEmp31QH9JDYJXvwh9pma8ap5Phxk6H", name: "Hinode Technologies", iconUrl: "", brandColor: "" },
  { pubKey: "ReFiSbuMcV8PMYcpvm9RmHDhF9HR3qyxsHZgf359NUx", name: "ReFi Hub", iconUrl: "", brandColor: "" },
  { pubKey: "sT34kbaqmHWbPwjhyeG1GnjoX82KpXawFsnzUkzJpYX", name: "SteakStache", iconUrl: "", brandColor: "" },
  { pubKey: "G1EAMrJcvzs5SwqAQRgDTjYBEGrxxJVwNS7qiUtB3akg", name: "Gleam", iconUrl: "", brandColor: "" },
  { pubKey: "FXcZJuQwkcQpw2YrkTaxWJ6rnw4P12wvULttviMRn655", name: "Serhio911", iconUrl: "", brandColor: "" },
  { pubKey: "DEgenL35vQWg3pE8rvY2vJ2SrmpMsXMecu4PmvJcCCJv", name: "DegenBot", iconUrl: "", brandColor: "" },
  { pubKey: "7k6puiEcBsMABVJPqF8dRPc2LG5H4ewBR9aDhRChxfwb", name: "Decomissioning node, redelegate by Feb 23", iconUrl: "", brandColor: "" },
  { pubKey: "EATzgj3KL3NAkaSKv8JFXPJahGueMbvTdVZj4zD9nQiV", name: "EAT TRIBE", iconUrl: "", brandColor: "" },
  { pubKey: "DhU3Q2NoCxU5ArXJWm3zxFDRuBiPU4fGrJ8kUasPxMnQ", name: "Khaos", iconUrl: "", brandColor: "" },
  { pubKey: "rapxbkwBSSvtqRFrsY83f51oUuZNuVXci74MuzYhiCy", name: "Raposa Coffee", iconUrl: "", brandColor: "" },
  { pubKey: "2PEyBgsPYBQ8pMdXQtEaPGNqWQHE9GCnmV2tTVN4GMru", name: "Private", iconUrl: "", brandColor: "" },
  { pubKey: "QUANT7qKUEW4PS4eP9jq4K35rDHpgWkWcgjbW1CwnGJ", name: "Quantum Crypto", iconUrl: "", brandColor: "" },
  { pubKey: "7rwEPPMQgHr3mn5nQX27SADt3tR8yucBgsNapYdrqRhB", name: "SOLAnode", iconUrl: "", brandColor: "" },
  { pubKey: "5yHqB3NxovCEMUniQCboaPRMyyQ7kQQF4QqvC4vaz78z", name: "EWR Validator", iconUrl: "", brandColor: "" },
  { pubKey: "8jxSHbS4qAnh5yueFp4D9ABXubKqMwXqF3HtdzQGuphp", name: "Chainlayer", iconUrl: "", brandColor: "" },
  { pubKey: "EdkhvJYa3kWQkFJAPzmGsQyi1D2JA5a7vwWw4hDuwbt", name: "Tartan | RaggedSec", iconUrl: "", brandColor: "" },
  { pubKey: "EtMSc3MvcDXUr6ChK5GxyFVwTxYA3zqP5XzjE9jwKvSV", name: "佛金疯 Solana Chinese Community", iconUrl: "", brandColor: "" },
  { pubKey: "DzPT1ZWDeURdTj38QBSceWnrpYFxZRBLPRXmUgHVDAGR", name: "YYDS Validator", iconUrl: "", brandColor: "" },
  { pubKey: "21oUQzzytWh6y3G3SQ7ehktMh1RrbsJNA4R5pAMNyyrG", name: "Range", iconUrl: "", brandColor: "" },
  { pubKey: "MicobSZgB9CZNvmnFSYbEtMjy7CUui5o6P3XoGTwZC5", name: "MICOBO", iconUrl: "", brandColor: "" },
  { pubKey: "LiFiDDUsf6GCRHwkHzW4YnR1QErj99MAU9diwb8TvWk", name: "LI.FI", iconUrl: "", brandColor: "" },
  { pubKey: "BtuCWGCncwPkxBYkxSL4UBLAXxwhfLCYufp6Pucc8LnM", name: "Onii-chan~", iconUrl: "", brandColor: "" },
  { pubKey: "MFLKX9vSfWXa4ZcVVpp4GF64ZbNUiX9EjSqtqNMdFXB", name: "The Mindfolk", iconUrl: "", brandColor: "" },
  { pubKey: "P1TCHYwYPsNaNUK6fGkZzwXPjnYAMYRnUUv4c1TREee", name: "DePitch Academy", iconUrl: "", brandColor: "" },
  { pubKey: "5HScvYkTWL9iojhPv26xK7GqB7oBsj9A2qHCeNRFmdyG", name: "ex1arey", iconUrl: "", brandColor: "" },
  { pubKey: "41HgiTYQ3qDWFW8jSDkecH2mEHUqZsmwFGDPndtmyLDR", name: "MeshMap", iconUrl: "", brandColor: "" },
  { pubKey: "4GEEKSwzc242QKF1uzzodpFaxb4GShQEZhkZfeXd27Vi", name: "Sol4Geeks", iconUrl: "", brandColor: "" },
  { pubKey: "2ve7kgjvaDZhMPq2nXhvGLno8sPJ8BAEdCvza384PyC8", name: "DataHive AI", iconUrl: "", brandColor: "" },
  { pubKey: "Gar9q7Ru2sKfVxFnR5xmV8GieJeUSTp7Uf3ixai9BQKS", name: "EAC", iconUrl: "", brandColor: "" },
  { pubKey: "4HUU6x8y8A22PWy5gUXwLzDfPg5pqkGpGqN2bKti7Kqk", name: "Solai Limited (NYSE: SLAI)", iconUrl: "", brandColor: "" },
  { pubKey: "2mxWiqtwdpE8zgkWxwFaJLn127dbuuHY4D32d8A6UnPL", name: "DSRV", iconUrl: "", brandColor: "" },
  { pubKey: "R2D2vs3bJwpNF2ejaB6UW1JdCZ5VstuAmuwxDuUUWNj", name: "RoboRun.xyz", iconUrl: "", brandColor: "" },
  { pubKey: "H7fXvnLCKtZqJBTipxeseabGfAZUdHJ9XuP6hCKrbvUb", name: "thugDAO Validator", iconUrl: "", brandColor: "" },
  { pubKey: "8inoRcYLtHdDL1qHWvGph7pkJKuJdrE2kNkFpjcYaYHf", name: "Puerta del Sol", iconUrl: "", brandColor: "" },
  { pubKey: "sENda1ZL5hoQUMpWbvRpReEfkrM4F35g9GBXPpYaZ9v", name: "SendAI Inc.", iconUrl: "", brandColor: "" },
  { pubKey: "QodirbUG8AZQBWpHhPJPfjj1xg4AaQUZCVVtwT8YfPi", name: "UZB Validator", iconUrl: "", brandColor: "" },
  { pubKey: "DZViGjfD4um4GQaNEE1h8tmWtMpgCW6qcvPBuHCyLwRX", name: "DoubleZero x RockawayX", iconUrl: "", brandColor: "" },
  { pubKey: "FEjcS4JCTqitjzW4Zj3Va2ioZZKf7MqsCMnrrgGLSvjm", name: "Block Rush Validator", iconUrl: "", brandColor: "" },
  { pubKey: "FbDPRNQZkCuDGsAbmRj1JbbXLzCiU6K8hSWRrL9RZqct", name: "EU Node", iconUrl: "", brandColor: "" },
  { pubKey: "7YCDRyGNn8g3WgZg25JLB9wKuERMkj99AFc8zHAQVwSt", name: "Steel Nerves", iconUrl: "", brandColor: "" },
  { pubKey: "dzufrE42PJjNNRBstdmunAdeDToDA3Cax6WDpFVj36Y", name: "IBRL", iconUrl: "", brandColor: "" },
  { pubKey: "49ufmzpErLmn7jAeP666i8nMdXhFuvzjCbQwf2oEMkN3", name: "Anza_New_Stake", iconUrl: "", brandColor: "" },
  { pubKey: "B48pw5uXH7gkCibuCBPE6nezKsCmYfFFwveCeMHpq4iv", name: "Buffalo Steve", iconUrl: "", brandColor: "" },
  { pubKey: "7MKUXUiiVeWFwLaNyw5exkujXnen5yB77hQa54KLD98h", name: "Fidelity Center for Applied Technology (FCAT®)", iconUrl: "", brandColor: "" },
  { pubKey: "7rFAeD5UT4fy8cQCnY8Y5F8GW1Wgw345Nxb7diXu5cjG", name: "maximka", iconUrl: "", brandColor: "" },
  { pubKey: "3dXXxEaV4fZqw1PL7VezfDkiJV5W4WTtRjh2EHgKSthF", name: "Hedgehog Spiky Validator", iconUrl: "", brandColor: "" },
  { pubKey: "SAFUitvicp7bGv9pbYhRJB5wu4doALqR5xB22V6EDjQ", name: "SOLMECH", iconUrl: "", brandColor: "" },
  { pubKey: "68q1YeY3QJoL3DF3umVKkCFARYh931sQTbZbRtYthGu9", name: "OrbitFlare Validator", iconUrl: "", brandColor: "" },
  { pubKey: "DGB2xq1gP7d74HAsuVShUskoU3dmoKuotFDtoPr2kFVT", name: "Rancho Stake", iconUrl: "", brandColor: "" },
  { pubKey: "1oH9rfyrbKoP7ucJ1Zr2HLHmDU8N6G1G6dEuruFsSqy", name: "AiSol", iconUrl: "", brandColor: "" },
  { pubKey: "GLAMvLYFVzzgXPEjwdTKFqXShckYvFaF3Z1r81Pr8UtW", name: "GLAM *.+", iconUrl: "", brandColor: "" },
  { pubKey: "59uncaiGG7RMfH6yMc6tLR69d61aT5yEcJq6ccq5Xbbu", name: "ZAN", iconUrl: "", brandColor: "" },
  { pubKey: "kaosFcskhYZCQidKKmkUSQLAqwpz3vtPpyyZ67N5NwA", name: "Aepalizage", iconUrl: "", brandColor: "" },
  { pubKey: "HYUU9pLdZRXsMSy3efikYHLKagtubP2UZYtmfwP9FXpu", name: "Blocmates X Firstset", iconUrl: "", brandColor: "" },
  { pubKey: "kawiL1oKtakS5xXsmeWKV9ubUJPtdgBrRU9EgHGDADf", name: "Kawil", iconUrl: "", brandColor: "" },
  { pubKey: "chopjqMvdGWRcrcuC1r8LmAzz9obXi1gSYPYM6zimWa", name: "Choplet Studios", iconUrl: "", brandColor: "" },
  { pubKey: "EjyNztuWsaiVFnEB3M6NSut6p6e8UHsUdE8BkmRLMHWp", name: "StakeWave", iconUrl: "", brandColor: "" },
  { pubKey: "DTELA4aHtJB8zcMJvKgcUjAYfkGcKdRUN77cpFoMVgxz", name: "dTelecom", iconUrl: "", brandColor: "" },
  { pubKey: "8uYxWYaRz9a3WPvE2LEgEp6sSfTCTRnRx54yKxdRGgsL", name: "Valor Node Capital", iconUrl: "", brandColor: "" },
  { pubKey: "StepeLdhJ2znRjHcZdjwMWsC4nTRURNKQY8Nca82LJp", name: "Step Finance", iconUrl: "", brandColor: "" },
  { pubKey: "Lua298Woc4rgcswL64yfWAL4EW44FgBZeLsKforf6tJ", name: "Lua Sol Foundation", iconUrl: "", brandColor: "" },
  { pubKey: "8cuBK2vJeqfukvSJQ2vaGDEBSnBoVD16L74SuHdnKjs8", name: "marcograss", iconUrl: "", brandColor: "" },
  { pubKey: "5ni6KoVM62cRJNfFFKGdiyDfYbKWWAGZ21cfGZcj1y66", name: "Custodian", iconUrl: "", brandColor: "" },
  { pubKey: "AEtdq4CwtuktCEUWLLpRTNPBZs6tr7BBqxkHJ1DjAttR", name: "DAIN", iconUrl: "", brandColor: "" },
  { pubKey: "B38JgkTi7Fu2Uxk8JzNw4M7aMhVxzGu2fsRqHNScPkCQ", name: "Dan's Validator", iconUrl: "", brandColor: "" },
  { pubKey: "6559KMdiUseNSAkRcK9WcFcNTppoj6jWtKVedpMkBYCn", name: "private valid s2", iconUrl: "", brandColor: "" },
  { pubKey: "5AC692spnjbegP7ttCXJEzUe8S81sLYsqJd8Ae6Zv1xU", name: "Majestysol", iconUrl: "", brandColor: "" },
  { pubKey: "DZVyygR326SerwzVivgqb8REnegEyU4teMkGQaBV6Bpw", name: "DoubleZero x Asymmetric Research", iconUrl: "", brandColor: "" },
  { pubKey: "FXRu5NA4ouLGFuZNNWZFwwnvQz9zE7JCX3D23RJTc2NU", name: "Bitprim SOL Validator", iconUrl: "", brandColor: "" },
  { pubKey: "6fCLXKxDSNMv5tXDdq3s6diaKVtP4pWLiLixVnDaWJvQ", name: "Frankendancer-DoubleZero4", iconUrl: "", brandColor: "" },
  { pubKey: "burnn86ebxJnhtk3cfpHoZxy5nUaC3K9U8VwzgqhEEt", name: "Sol-Incinerator", iconUrl: "", brandColor: "" },
  { pubKey: "BfxZj7ckfRGHxByn7aHgH2puyXhfjAUvULtRjJo4rd8C", name: "Cryptology", iconUrl: "", brandColor: "" },
  { pubKey: "AGXZemZbyZjz5NBhufcob2pf8AXnr9HaGFUGNCfooWrB", name: "RockX", iconUrl: "", brandColor: "" },
  { pubKey: "eondcw2upjH14EuvBzmn6HfGEGo8t9hG9JbXtPj6cym", name: "EONpool", iconUrl: "", brandColor: "" },
  { pubKey: "EPrq1DvsWqX9CHBKgMU7gxvNvPbqRLhbqz2QzHcPFzab", name: "Kangaroo", iconUrl: "", brandColor: "" },
  { pubKey: "kWEiSEQZMeLAbMUiz1njRTZEjuSpJDCgVynB6pJHpcr", name: "Viking", iconUrl: "", brandColor: "" },
  { pubKey: "37BPVW1Ne1XHrzK15xguAS2BTdobVfThDzTE2mv8SsnJ", name: "InfStones", iconUrl: "", brandColor: "" },
  { pubKey: "EpRvips2doUUdxvs3Qhf4MCLqVeJEPu47Aci5QbBXASV", name: "EpRvips2doUUdxvs3Qhf4MCLqVeJEPu47Aci5QbBXASV", iconUrl: "", brandColor: "" },
  { pubKey: "4GWXbzZFntDor4S25siX1tSWFv7Q6hHsHcKGzHQJK7QB", name: "Google Cloud Web3", iconUrl: "", brandColor: "" },
  { pubKey: "etherfVmEL2ymvdhjAm3FKGdrJECFaG3cZ3ktZvQ2yX", name: "Etherfuse", iconUrl: "", brandColor: "" },
  { pubKey: "6jf9Hwx4ChqUpi8skCqmh7bnfTWXHXsqbfqAPHmSzPYc", name: "Figment | Firedancer", iconUrl: "", brandColor: "" },
  { pubKey: "Fy6zNoZ1eCPpQX3JXeQ9Yd1HW1BFL8rrFmDvYYDnuxjT", name: "Anti", iconUrl: "", brandColor: "" },
  { pubKey: "MS1kjUoVPfy4AgyJLiJ3eC6Gv34Cwr839MryJgNKdwJ", name: "Toshi CSS", iconUrl: "", brandColor: "" },
  { pubKey: "ERk9Cs3b6F6pHALUnCiw7NNDTsjDRcgQPYNBTPLbok8u", name: "JumpSOL - Solana Labs", iconUrl: "", brandColor: "" },
  { pubKey: "EMVmh5hF6LT1sZM9G7dEX1bykRYEymWY2vtE7QHBBAW6", name: "OmegaNode Validator", iconUrl: "", brandColor: "" },
  { pubKey: "4Mb8vvxRKfS1oY15RWiHz65v3oFbn6wd4dnVGKJFaBWC", name: "ZionX", iconUrl: "", brandColor: "" },
  { pubKey: "DLKjd8DJc9NajCaHPeQL6BnhPi3a4BZm7zCdVF3MzDRZ", name: "Frankendancer-DoubleZero1", iconUrl: "", brandColor: "" },
  { pubKey: "8r4Fu6M8brgnL456RJfwxk8kN4iw1LgczfuXeuG1g4px", name: "Frankendancer-DoubleZero3", iconUrl: "", brandColor: "" },
  { pubKey: "P1ayLpEHHVagavo2WGM3Rp9KKxwYU2VKQrfjdXGmKt1", name: "Play Solana", iconUrl: "", brandColor: "" },
  { pubKey: "R1vAoSPFQdCc6wsAEMtxWXjqptSeN1YUiq2Zni1of21", name: "Superfast", iconUrl: "", brandColor: "" },
  { pubKey: "proofK5zwB5eo5q6UWnFKiDHxyh8wopP5Bq1aXVnouw", name: "Proof Group", iconUrl: "", brandColor: "" },
  { pubKey: "BUgQ241MWNkRGwEYww4VNtLxTZNb92YUzxwtNx7shrk", name: "Blockchain at USC", iconUrl: "", brandColor: "" },
  { pubKey: "ATRFbtnsDd9ka3eZooTPixm3AjicHxod1BAhNYBMsj8K", name: "Fire of Anatolia", iconUrl: "", brandColor: "" },
  { pubKey: "C2bJpaAU2cBupABkV5p9ed37sn7z8f2nfXqZ1gFBNBvv", name: "martta555", iconUrl: "", brandColor: "" },
];